	.align 2
DirectSoundWaveData_08103134::
	.incbin "sound/direct_sound_samples/08103134.bin"

	.align 2
DirectSoundWaveData_081067FC::
	.incbin "sound/direct_sound_samples/081067FC.bin"

	.align 2
DirectSoundWaveData_081085FC::
	.incbin "sound/direct_sound_samples/081085FC.bin"

	.align 2
DirectSoundWaveData_0810C0E0::
	.incbin "sound/direct_sound_samples/0810C0E0.bin"

	.align 2
DirectSoundWaveData_0810E2E0::
	.incbin "sound/direct_sound_samples/0810E2E0.bin"

	.align 2
DirectSoundWaveData_0811043C::
	.incbin "sound/direct_sound_samples/0811043C.bin"

	.align 2
DirectSoundWaveData_08113FB8::
	.incbin "sound/direct_sound_samples/08113FB8.bin"

	.align 2
DirectSoundWaveData_081161B4::
	.incbin "sound/direct_sound_samples/081161B4.bin"

	.align 2
DirectSoundWaveData_08119168::
	.incbin "sound/direct_sound_samples/08119168.bin"

	.align 2
DirectSoundWaveData_0811A584::
	.incbin "sound/direct_sound_samples/0811A584.bin"

	.align 2
DirectSoundWaveData_0811B9BC::
	.incbin "sound/direct_sound_samples/0811B9BC.bin"

	.align 2
DirectSoundWaveData_0811DDB0::
	.incbin "sound/direct_sound_samples/0811DDB0.bin"

	.align 2
DirectSoundWaveData_0812132C::
	.incbin "sound/direct_sound_samples/0812132C.bin"

	.align 2
DirectSoundWaveData_0812213C::
	.incbin "sound/direct_sound_samples/0812213C.bin"

	.align 2
DirectSoundWaveData_08124EE0::
	.incbin "sound/direct_sound_samples/08124EE0.bin"

	.align 2
DirectSoundWaveData_08126F60::
	.incbin "sound/direct_sound_samples/08126F60.bin"

	.align 2
DirectSoundWaveData_08129A04::
	.incbin "sound/direct_sound_samples/08129A04.bin"

	.align 2
DirectSoundWaveData_0812B804::
	.incbin "sound/direct_sound_samples/0812B804.bin"

	.align 2
DirectSoundWaveData_0812EC68::
	.incbin "sound/direct_sound_samples/0812EC68.bin"

	.align 2
DirectSoundWaveData_081312A0::
	.incbin "sound/direct_sound_samples/081312A0.bin"

	.align 2
DirectSoundWaveData_08133FF4::
	.incbin "sound/direct_sound_samples/08133FF4.bin"

	.align 2
DirectSoundWaveData_081350B8::
	.incbin "sound/direct_sound_samples/081350B8.bin"

	.align 2
DirectSoundWaveData_0813825C::
	.incbin "sound/direct_sound_samples/0813825C.bin"

	.align 2
DirectSoundWaveData_08138914::
	.incbin "sound/direct_sound_samples/08138914.bin"

	.align 2
DirectSoundWaveData_0813B918::
	.incbin "sound/direct_sound_samples/0813B918.bin"

	.align 2
DirectSoundWaveData_0813C8B8::
	.incbin "sound/direct_sound_samples/0813C8B8.bin"

	.align 2
DirectSoundWaveData_0813ED38::
	.incbin "sound/direct_sound_samples/0813ED38.bin"

	.align 2
DirectSoundWaveData_08140F30::
	.incbin "sound/direct_sound_samples/08140F30.bin"

	.align 2
DirectSoundWaveData_08142DCC::
	.incbin "sound/direct_sound_samples/08142DCC.bin"

	.align 2
DirectSoundWaveData_08143F6C::
	.incbin "sound/direct_sound_samples/08143F6C.bin"

	.align 2
DirectSoundWaveData_081453B8::
	.incbin "sound/direct_sound_samples/081453B8.bin"

	.align 2
DirectSoundWaveData_081461FC::
	.incbin "sound/direct_sound_samples/081461FC.bin"

	.align 2
DirectSoundWaveData_08146764::
	.incbin "sound/direct_sound_samples/08146764.bin"

	.align 2
DirectSoundWaveData_08146CE4::
	.incbin "sound/direct_sound_samples/08146CE4.bin"

	.align 2
DirectSoundWaveData_08147690::
	.incbin "sound/direct_sound_samples/08147690.bin"

	.align 2
DirectSoundWaveData_08147C54::
	.incbin "sound/direct_sound_samples/08147C54.bin"

	.align 2
DirectSoundWaveData_081480B8::
	.incbin "sound/direct_sound_samples/081480B8.bin"

	.align 2
DirectSoundWaveData_08148820::
	.incbin "sound/direct_sound_samples/08148820.bin"

	.align 2
DirectSoundWaveData_08149188::
	.incbin "sound/direct_sound_samples/08149188.bin"

	.align 2
DirectSoundWaveData_0814A774::
	.incbin "sound/direct_sound_samples/0814A774.bin"

	.align 2
DirectSoundWaveData_0814B174::
	.incbin "sound/direct_sound_samples/0814B174.bin"

	.align 2
DirectSoundWaveData_0814BD08::
	.incbin "sound/direct_sound_samples/0814BD08.bin"

	.align 2
DirectSoundWaveData_0814D5AC::
	.incbin "sound/direct_sound_samples/0814D5AC.bin"

	.align 2
DirectSoundWaveData_0814E630::
	.incbin "sound/direct_sound_samples/0814E630.bin"

	.align 2
DirectSoundWaveData_0814E748::
	.incbin "sound/direct_sound_samples/0814E748.bin"

	.align 2
DirectSoundWaveData_0814EF50::
	.incbin "sound/direct_sound_samples/0814EF50.bin"

	.align 2
DirectSoundWaveData_0814F4D0::
	.incbin "sound/direct_sound_samples/0814F4D0.bin"

	.align 2
DirectSoundWaveData_0814FB78::
	.incbin "sound/direct_sound_samples/0814FB78.bin"

	.align 2
DirectSoundWaveData_08151870::
	.incbin "sound/direct_sound_samples/08151870.bin"

	.align 2
DirectSoundWaveData_0815336C::
	.incbin "sound/direct_sound_samples/0815336C.bin"

	.align 2
DirectSoundWaveData_08153924::
	.incbin "sound/direct_sound_samples/08153924.bin"

	.align 2
DirectSoundWaveData_08154448::
	.incbin "sound/direct_sound_samples/08154448.bin"

	.align 2
DirectSoundWaveData_081550AC::
	.incbin "sound/direct_sound_samples/081550AC.bin"

	.align 2
DirectSoundWaveData_08155C50::
	.incbin "sound/direct_sound_samples/08155C50.bin"

	.align 2
DirectSoundWaveData_08156980::
	.incbin "sound/direct_sound_samples/08156980.bin"

	.align 2
DirectSoundWaveData_081575C4::
	.incbin "sound/direct_sound_samples/081575C4.bin"

	.align 2
DirectSoundWaveData_08158020::
	.incbin "sound/direct_sound_samples/08158020.bin"

	.align 2
DirectSoundWaveData_081585E8::
	.incbin "sound/direct_sound_samples/081585E8.bin"

	.align 2
DirectSoundWaveData_0815B2C8::
	.incbin "sound/direct_sound_samples/0815B2C8.bin"

	.align 2
DirectSoundWaveData_0815C470::
	.incbin "sound/direct_sound_samples/0815C470.bin"

	.align 2
DirectSoundWaveData_0815D4E4::
	.incbin "sound/direct_sound_samples/0815D4E4.bin"

	.align 2
DirectSoundWaveData_081607E0::
	.incbin "sound/direct_sound_samples/081607E0.bin"

	.align 2
DirectSoundWaveData_08161EB0::
	.incbin "sound/direct_sound_samples/08161EB0.bin"

	.align 2
DirectSoundWaveData_08162A4C::
	.incbin "sound/direct_sound_samples/08162A4C.bin"

	.align 2
DirectSoundWaveData_081630F0::
	.incbin "sound/direct_sound_samples/081630F0.bin"

	.align 2
DirectSoundWaveData_08164E4C::
	.incbin "sound/direct_sound_samples/08164E4C.bin"

	.align 2
DirectSoundWaveData_081651EC::
	.incbin "sound/direct_sound_samples/081651EC.bin"

	.align 2
DirectSoundWaveData_08165810::
	.incbin "sound/direct_sound_samples/08165810.bin"

	.align 2
DirectSoundWaveData_081661E4::
	.incbin "sound/direct_sound_samples/081661E4.bin"

	.align 2
DirectSoundWaveData_08166B70::
	.incbin "sound/direct_sound_samples/08166B70.bin"

	.align 2
DirectSoundWaveData_08167850::
	.incbin "sound/direct_sound_samples/08167850.bin"

	.align 2
DirectSoundWaveData_08168138::
	.incbin "sound/direct_sound_samples/08168138.bin"

	.align 2
DirectSoundWaveData_08168554::
	.incbin "sound/direct_sound_samples/08168554.bin"

	.align 2
DirectSoundWaveData_081690F8::
	.incbin "sound/direct_sound_samples/081690F8.bin"

	.align 2
DirectSoundWaveData_08169F80::
	.incbin "sound/direct_sound_samples/08169F80.bin"

	.align 2
DirectSoundWaveData_0816A324::
	.incbin "sound/direct_sound_samples/0816A324.bin"

	.align 2
DirectSoundWaveData_0816B308::
	.incbin "sound/direct_sound_samples/0816B308.bin"

	.align 2
DirectSoundWaveData_0816B894::
	.incbin "sound/direct_sound_samples/0816B894.bin"

	.align 2
DirectSoundWaveData_0816E798::
	.incbin "sound/direct_sound_samples/0816E798.bin"

	.align 2
DirectSoundWaveData_0816FAAC::
	.incbin "sound/direct_sound_samples/0816FAAC.bin"

	.align 2
DirectSoundWaveData_08172438::
	.incbin "sound/direct_sound_samples/08172438.bin"

	.align 2
DirectSoundWaveData_08174974::
	.incbin "sound/direct_sound_samples/08174974.bin"

	.align 2
DirectSoundWaveData_081769CC::
	.incbin "sound/direct_sound_samples/081769CC.bin"

	.align 2
DirectSoundWaveData_08178D24::
	.incbin "sound/direct_sound_samples/08178D24.bin"

	.align 2
DirectSoundWaveData_08179498::
	.incbin "sound/direct_sound_samples/08179498.bin"

	.align 2
DirectSoundWaveData_081850E0::
	.incbin "sound/direct_sound_samples/081850E0.bin"

	.align 2
DirectSoundWaveData_08188FC0::
	.incbin "sound/direct_sound_samples/08188FC0.bin"

	.align 2
DirectSoundWaveData_0818B73C::
	.incbin "sound/direct_sound_samples/0818B73C.bin"

	.align 2
DirectSoundWaveData_0818DD3C::
	.incbin "sound/direct_sound_samples/0818DD3C.bin"

	.align 2
DirectSoundWaveData_081900E0::
	.incbin "sound/direct_sound_samples/081900E0.bin"

	.align 2
DirectSoundWaveData_08193948::
	.incbin "sound/direct_sound_samples/08193948.bin"

	.align 2
DirectSoundWaveData_08196D48::
	.incbin "sound/direct_sound_samples/08196D48.bin"

	.align 2
DirectSoundWaveData_081986B0::
	.incbin "sound/direct_sound_samples/081986B0.bin"

	.align 2
DirectSoundWaveData_0819A554::
	.incbin "sound/direct_sound_samples/0819A554.bin"

	.align 2
DirectSoundWaveData_081AC4EC::
	.incbin "sound/direct_sound_samples/081AC4EC.bin"

	.align 2
DirectSoundWaveData_081B54F0::
	.incbin "sound/direct_sound_samples/081B54F0.bin"

	.align 2
DirectSoundWaveData_081B6CDC::
	.incbin "sound/direct_sound_samples/081B6CDC.bin"

	.align 2
DirectSoundWaveData_081BB938::
	.incbin "sound/direct_sound_samples/081BB938.bin"

	.align 2
DirectSoundWaveData_081BD240::
	.incbin "sound/direct_sound_samples/081BD240.bin"

	.align 2
DirectSoundWaveData_081BE96C::
	.incbin "sound/direct_sound_samples/081BE96C.bin"

	.align 2
DirectSoundWaveData_08400000::
	.incbin "sound/direct_sound_samples/08400000.bin"

	.align 2
DirectSoundWaveData_08403E60::
	.incbin "sound/direct_sound_samples/08403E60.bin"

	.align 2
DirectSoundWaveData_08406984::
	.incbin "sound/direct_sound_samples/08406984.bin"

	.align 2
DirectSoundWaveData_08417978::
	.incbin "sound/direct_sound_samples/08417978.bin"

	.align 2
DirectSoundWaveData_0841BE14::
	.incbin "sound/direct_sound_samples/0841BE14.bin"

	.align 2
DirectSoundWaveData_0842B458::
	.incbin "sound/direct_sound_samples/0842B458.bin"

	.align 2
DirectSoundWaveData_084363E8::
	.incbin "sound/direct_sound_samples/084363E8.bin"

	.align 2
DirectSoundWaveData_084449BC::
	.incbin "sound/direct_sound_samples/084449BC.bin"

	.align 2
DirectSoundWaveData_0845EABC::
	.incbin "sound/direct_sound_samples/0845EABC.bin"

	.align 2
DirectSoundWaveData_08472900::
	.incbin "sound/direct_sound_samples/08472900.bin"

	.align 2
DirectSoundWaveData_084876AC::
	.incbin "sound/direct_sound_samples/084876AC.bin"

	.align 2
DirectSoundWaveData_084ABEE4::
	.incbin "sound/direct_sound_samples/084ABEE4.bin"

	.align 2
DirectSoundWaveData_084CADF4::
	.incbin "sound/direct_sound_samples/084CADF4.bin"

	.align 2
DirectSoundWaveData_084F706C::
	.incbin "sound/direct_sound_samples/084F706C.bin"

	.align 2
DirectSoundWaveData_08518E78::
	.incbin "sound/direct_sound_samples/08518E78.bin"

	.align 2
DirectSoundWaveData_0852A8B8::
	.incbin "sound/direct_sound_samples/0852A8B8.bin"

	.align 2
DirectSoundWaveData_08550D8C::
	.incbin "sound/direct_sound_samples/08550D8C.bin"

	.align 2
DirectSoundWaveData_08573F44::
	.incbin "sound/direct_sound_samples/08573F44.bin"

	.align 2
DirectSoundWaveData_08574B1C::
	.incbin "sound/direct_sound_samples/08574B1C.bin"

	.align 2
DirectSoundWaveData_08580898::
	.incbin "sound/direct_sound_samples/08580898.bin"

	.align 2
DirectSoundWaveData_0858DCD8::
	.incbin "sound/direct_sound_samples/0858DCD8.bin"

	.align 2
DirectSoundWaveData_0859B024::
	.incbin "sound/direct_sound_samples/0859B024.bin"

	.align 2
DirectSoundWaveData_085A4A4C::
	.incbin "sound/direct_sound_samples/085A4A4C.bin"

	.align 2
DirectSoundWaveData_085AD4B8::
	.incbin "sound/direct_sound_samples/085AD4B8.bin"

	.align 2
DirectSoundWaveData_085AE860::
	.incbin "sound/direct_sound_samples/085AE860.bin"

	.align 2
DirectSoundWaveData_085B04B8::
	.incbin "sound/direct_sound_samples/085B04B8.bin"

	.align 2
DirectSoundWaveData_085B3C74::
	.incbin "sound/direct_sound_samples/085B3C74.bin"

	.align 2
DirectSoundWaveData_085B7928::
	.incbin "sound/direct_sound_samples/085B7928.bin"

	.align 2
DirectSoundWaveData_085BCC60::
	.incbin "sound/direct_sound_samples/085BCC60.bin"

	.align 2
DirectSoundWaveData_085C8C3C::
	.incbin "sound/direct_sound_samples/085C8C3C.bin"

	.align 2
DirectSoundWaveData_085DE3BC::
	.incbin "sound/direct_sound_samples/085DE3BC.bin"

	.align 2
DirectSoundWaveData_085F5550::
	.incbin "sound/direct_sound_samples/085F5550.bin"

	.align 2
DirectSoundWaveData_085F7D20::
	.incbin "sound/direct_sound_samples/085F7D20.bin"

	.align 2
DirectSoundWaveData_0860B22C::
	.incbin "sound/direct_sound_samples/0860B22C.bin"

	.align 2
DirectSoundWaveData_0860D500::
	.incbin "sound/direct_sound_samples/0860D500.bin"

	.align 2
DirectSoundWaveData_0860FD80::
	.incbin "sound/direct_sound_samples/0860FD80.bin"

	.align 2
DirectSoundWaveData_08611F00::
	.incbin "sound/direct_sound_samples/08611F00.bin"

	.align 2
DirectSoundWaveData_0861E4F0::
	.incbin "sound/direct_sound_samples/0861E4F0.bin"

	.align 2
DirectSoundWaveData_086249F0::
	.incbin "sound/direct_sound_samples/086249F0.bin"

	.align 2
DirectSoundWaveData_0862F578::
	.incbin "sound/direct_sound_samples/0862F578.bin"

	.align 2
DirectSoundWaveData_086313FC::
	.incbin "sound/direct_sound_samples/086313FC.bin"

	.align 2
DirectSoundWaveData_08634624::
	.incbin "sound/direct_sound_samples/08634624.bin"

	.align 2
DirectSoundWaveData_08637B10::
	.incbin "sound/direct_sound_samples/08637B10.bin"

	.align 2
DirectSoundWaveData_08639334::
	.incbin "sound/direct_sound_samples/08639334.bin"

	.align 2
DirectSoundWaveData_0864411C::
	.incbin "sound/direct_sound_samples/0864411C.bin"

	.align 2
DirectSoundWaveData_08647624::
	.incbin "sound/direct_sound_samples/08647624.bin"

	.align 2
DirectSoundWaveData_08652868::
	.incbin "sound/direct_sound_samples/08652868.bin"

	.align 2
DirectSoundWaveData_0866069C::
	.incbin "sound/direct_sound_samples/0866069C.bin"

	.align 2
DirectSoundWaveData_08663388::
	.incbin "sound/direct_sound_samples/08663388.bin"

	.align 2
DirectSoundWaveData_0866585C::
	.incbin "sound/direct_sound_samples/0866585C.bin"

	.align 2
DirectSoundWaveData_0867015C::
	.incbin "sound/direct_sound_samples/0867015C.bin"

	.align 2
DirectSoundWaveData_08677F54::
	.incbin "sound/direct_sound_samples/08677F54.bin"

	.align 2
DirectSoundWaveData_086866B0::
	.incbin "sound/direct_sound_samples/086866B0.bin"

	.align 2
DirectSoundWaveData_0869064C::
	.incbin "sound/direct_sound_samples/0869064C.bin"

	.align 2
DirectSoundWaveData_086B088C::
	.incbin "sound/direct_sound_samples/086B088C.bin"

	.align 2
DirectSoundWaveData_086CCED4::
	.incbin "sound/direct_sound_samples/086CCED4.bin"

	.align 2
DirectSoundWaveData_086D4938::
	.incbin "sound/direct_sound_samples/086D4938.bin"

	.align 2
DirectSoundWaveData_086E3558::
	.incbin "sound/direct_sound_samples/086E3558.bin"

	.align 2
DirectSoundWaveData_0870260C::
	.incbin "sound/direct_sound_samples/0870260C.bin"

	.align 2
DirectSoundWaveData_08703D20::
	.incbin "sound/direct_sound_samples/08703D20.bin"

	.align 2
DirectSoundWaveData_08708900::
	.incbin "sound/direct_sound_samples/08708900.bin"

	.align 2
DirectSoundWaveData_0870C288::
	.incbin "sound/direct_sound_samples/0870C288.bin"

	.align 2
DirectSoundWaveData_0870D4EC::
	.incbin "sound/direct_sound_samples/0870D4EC.bin"

	.align 2
DirectSoundWaveData_0870DE64::
	.incbin "sound/direct_sound_samples/0870DE64.bin"

	.align 2
DirectSoundWaveData_0870EE58::
	.incbin "sound/direct_sound_samples/0870EE58.bin"

	.align 2
DirectSoundWaveData_08714334::
	.incbin "sound/direct_sound_samples/08714334.bin"

	.align 2
DirectSoundWaveData_08731110::
	.incbin "sound/direct_sound_samples/08731110.bin"

	.align 2
DirectSoundWaveData_08737DFC::
	.incbin "sound/direct_sound_samples/08737DFC.bin"

	.align 2
DirectSoundWaveData_0873986C::
	.incbin "sound/direct_sound_samples/0873986C.bin"

	.align 2
DirectSoundWaveData_0873C494::
	.incbin "sound/direct_sound_samples/0873C494.bin"

	.align 2
DirectSoundWaveData_0873FA30::
	.incbin "sound/direct_sound_samples/0873FA30.bin"

	.align 2
DirectSoundWaveData_08753A08::
	.incbin "sound/direct_sound_samples/08753A08.bin"

	.align 2
DirectSoundWaveData_08757DD0::
	.incbin "sound/direct_sound_samples/08757DD0.bin"

	.align 2
DirectSoundWaveData_0876EB7C::
	.incbin "sound/direct_sound_samples/0876EB7C.bin"

	.align 2
DirectSoundWaveData_0877627C::
	.incbin "sound/direct_sound_samples/0877627C.bin"

	.align 2
DirectSoundWaveData_0878E880::
	.incbin "sound/direct_sound_samples/0878E880.bin"

	.align 2
DirectSoundWaveData_08790ED4::
	.incbin "sound/direct_sound_samples/08790ED4.bin"

	.align 2
DirectSoundWaveData_087926E4::
	.incbin "sound/direct_sound_samples/087926E4.bin"

	.align 2
DirectSoundWaveData_08793EEC::
	.incbin "sound/direct_sound_samples/08793EEC.bin"

	.align 2
DirectSoundWaveData_08795164::
	.incbin "sound/direct_sound_samples/08795164.bin"

	.align 2
DirectSoundWaveData_08795C34::
	.incbin "sound/direct_sound_samples/08795C34.bin"

	.align 2
DirectSoundWaveData_08796FE0::
	.incbin "sound/direct_sound_samples/08796FE0.bin"

	.align 2
DirectSoundWaveData_08799E90::
	.incbin "sound/direct_sound_samples/08799E90.bin"

	.align 2
DirectSoundWaveData_0879FA4C::
	.incbin "sound/direct_sound_samples/0879FA4C.bin"

	.align 2
DirectSoundWaveData_087A5430::
	.incbin "sound/direct_sound_samples/087A5430.bin"

	.align 2
DirectSoundWaveData_087A8E5C::
	.incbin "sound/direct_sound_samples/087A8E5C.bin"

@ Multiboot samples start here

	.align 2
DirectSoundWaveData_0202E9C8:
	.incbin "sound/direct_sound_samples/0202E9C8.bin"

	.align 2
DirectSoundWaveData_0202F2F0:
	.incbin "sound/direct_sound_samples/0202F2F0.bin"

	.align 2
DirectSoundWaveData_0202F7A8:
	.incbin "sound/direct_sound_samples/0202F7A8.bin"

	.align 2
DirectSoundWaveData_020300DC:
	.incbin "sound/direct_sound_samples/020300DC.bin"

	.align 2
DirectSoundWaveData_02030CB0:
	.incbin "sound/direct_sound_samples/02030CB0.bin"

	.align 2
DirectSoundWaveData_02031308:
	.incbin "sound/direct_sound_samples/02031308.bin"

	.align 2
DirectSoundWaveData_02031A88:
	.incbin "sound/direct_sound_samples/02031A88.bin"

	.align 2
DirectSoundWaveData_02032984:
	.incbin "sound/direct_sound_samples/02032984.bin"

	.align 2
DirectSoundWaveData_02033170:
	.incbin "sound/direct_sound_samples/02033170.bin"

	.align 2
DirectSoundWaveData_020334A0:
	.incbin "sound/direct_sound_samples/020334A0.bin"
