	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51_short::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51_short.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"

	.align 2
DirectSoundWaveData_orchhit::
	.incbin "sound/direct_sound_samples/orchhit.bin"

	.align 2
DirectSoundWaveData_organchord::
	.incbin "sound/direct_sound_samples/organchord.bin"

	.align 2
DirectSoundWaveData_octavestrings::
	.incbin "sound/direct_sound_samples/octavestrings.bin"

	.align 2
DirectSoundWaveData_octavestrings2::
	.incbin "sound/direct_sound_samples/octavestrings2.bin"

	.align 2
DirectSoundWaveData_duty::
	.incbin "sound/direct_sound_samples/synth/duty.bin"

	.align 2
DirectSoundWaveData_saw::
	.incbin "sound/direct_sound_samples/synth/saw.bin"

	.align 2
DirectSoundWaveData_triangle::
	.incbin "sound/direct_sound_samples/synth/triangle.bin"

    .align 2
DirectSoundWaveData_sc88pro_vibraphone_36::
    .incbin "sound/direct_sound_samples/sc88pro_vibraphone_36.bin"

    .align 2
DirectSoundWaveData_sc88pro_vibraphone_48::
    .incbin "sound/direct_sound_samples/sc88pro_vibraphone_48.bin"

    .align 2
DirectSoundWaveData_sc88pro_vibraphone_60::
    .incbin "sound/direct_sound_samples/sc88pro_vibraphone_60.bin"

    .align 2
DirectSoundWaveData_sc88pro_vibraphone_84::
    .incbin "sound/direct_sound_samples/sc88pro_vibraphone_84.bin"

    .align 2
DirectSoundWaveData_sc88pro_violin::
    .incbin "sound/direct_sound_samples/sc88pro_violin.bin"

    .align 2
DirectSoundWaveData_sd90_classical_violin::
    .incbin "sound/direct_sound_samples/sd90_classical_violin.bin"

    .align 2
DirectSoundWaveData_sc88pro_castanets::
    .incbin "sound/direct_sound_samples/sc88pro_castanets.bin"

    .align 2
DirectSoundWaveData_sc88pro_high_wood_block::
    .incbin "sound/direct_sound_samples/sc88pro_high_wood_block.bin"

	.align 2
DirectSoundWaveData_sine::
	.incbin "sound/direct_sound_samples/sine.bin"

	.align 2
DirectSoundWaveData_startup::
	.incbin "sound/direct_sound_samples/startup.bin"

	.align 2
DirectSoundWaveData_square25::
	.incbin "sound/direct_sound_samples/square25.bin"

	.align 2
DirectSoundWaveData_square_12_c2::
	.incbin "sound/direct_sound_samples/12_c2.bin"

	.align 2
DirectSoundWaveData_square_12_c3::
	.incbin "sound/direct_sound_samples/12_c3.bin"

	.align 2
DirectSoundWaveData_square_12_c4::
	.incbin "sound/direct_sound_samples/12_c4.bin"

	.align 2
DirectSoundWaveData_square_12_c5::
	.incbin "sound/direct_sound_samples/12_c5.bin"

	.align 2
DirectSoundWaveData_square_25_c2::
	.incbin "sound/direct_sound_samples/25_c2.bin"

	.align 2
DirectSoundWaveData_square_25_c3::
	.incbin "sound/direct_sound_samples/25_c3.bin"

	.align 2
DirectSoundWaveData_square_25_c4::
	.incbin "sound/direct_sound_samples/25_c4.bin"

	.align 2
DirectSoundWaveData_square_25_c5::
	.incbin "sound/direct_sound_samples/25_c5.bin"

	.align 2
DirectSoundWaveData_square_50_c2::
	.incbin "sound/direct_sound_samples/50_c2.bin"

	.align 2
DirectSoundWaveData_square_50_c3::
	.incbin "sound/direct_sound_samples/50_c3.bin"

	.align 2
DirectSoundWaveData_square_50_c4::
	.incbin "sound/direct_sound_samples/50_c4.bin"

	.align 2
DirectSoundWaveData_square_50_c5::
	.incbin "sound/direct_sound_samples/50_c5.bin"

	.align 2
DirectSoundWaveData_square_75_c2::
	.incbin "sound/direct_sound_samples/75_c2.bin"

	.align 2
DirectSoundWaveData_square_75_c3::
	.incbin "sound/direct_sound_samples/75_c3.bin"

	.align 2
DirectSoundWaveData_square_75_c4::
	.incbin "sound/direct_sound_samples/75_c4.bin"

	.align 2
DirectSoundWaveData_square_75_c5::
	.incbin "sound/direct_sound_samples/75_c5.bin"

    .align 2
crown_2clara4:
	.incbin "sound/direct_sound_samples/crown_2clara4.bin"

    .align 2
crown_2clarc4:
	.incbin "sound/direct_sound_samples/crown_2clarc4.bin"

    .align 2
crown_2clarg5:
	.incbin "sound/direct_sound_samples/crown_2clarg5.bin"

    .align 2
crown_80brsc3:
	.incbin "sound/direct_sound_samples/crown_80brsc3.bin"

    .align 2
crown_80brsc4:
	.incbin "sound/direct_sound_samples/crown_80brsc4.bin"

    .align 2
crown_80brsc5:
	.incbin "sound/direct_sound_samples/crown_80brsc5.bin"

    .align 2
crown_80brsds6:
	.incbin "sound/direct_sound_samples/crown_80brsds6.bin"

    .align 2
crown_80brsgs5:
	.incbin "sound/direct_sound_samples/crown_80brsgs5.bin"

    .align 2
crown_adchh:
	.incbin "sound/direct_sound_samples/crown_adchh.bin"

    .align 2
crown_adcowbl:
	.incbin "sound/direct_sound_samples/crown_adcowbl.bin"

    .align 2
crown_adcrash1:
	.incbin "sound/direct_sound_samples/crown_adcrash1.bin"

    .align 2
crown_adcrash2:
	.incbin "sound/direct_sound_samples/crown_adcrash2.bin"

    .align 2
crown_adjazchh:
	.incbin "sound/direct_sound_samples/crown_adjazchh.bin"

    .align 2
crown_adjazcrash:
	.incbin "sound/direct_sound_samples/crown_adjazcrash.bin"

    .align 2
crown_adjazkick:
	.incbin "sound/direct_sound_samples/crown_adjazkick.bin"

    .align 2
crown_adjazohh:
	.incbin "sound/direct_sound_samples/crown_adjazohh.bin"

    .align 2
crown_adjazphh:
	.incbin "sound/direct_sound_samples/crown_adjazphh.bin"

    .align 2
crown_adjazrbel:
	.incbin "sound/direct_sound_samples/crown_adjazrbel.bin"

    .align 2
crown_adjazride:
	.incbin "sound/direct_sound_samples/crown_adjazride.bin"

    .align 2
crown_adjazsnare:
	.incbin "sound/direct_sound_samples/crown_adjazsnare.bin"

    .align 2
crown_adkick:
	.incbin "sound/direct_sound_samples/crown_adkick.bin"

    .align 2
crown_adohh:
	.incbin "sound/direct_sound_samples/crown_adohh.bin"

    .align 2
crown_adphh:
	.incbin "sound/direct_sound_samples/crown_adphh.bin"

    .align 2
crown_adrbel:
	.incbin "sound/direct_sound_samples/crown_adrbel.bin"

    .align 2
crown_adride:
	.incbin "sound/direct_sound_samples/crown_adride.bin"

    .align 2
crown_adsidestk:
	.incbin "sound/direct_sound_samples/crown_adsidestk.bin"

    .align 2
crown_adsnare:
	.incbin "sound/direct_sound_samples/crown_adsnare.bin"

    .align 2
crown_adtom1:
	.incbin "sound/direct_sound_samples/crown_adtom1.bin"

    .align 2
crown_adtom2:
	.incbin "sound/direct_sound_samples/crown_adtom2.bin"

    .align 2
crown_adtom4:
	.incbin "sound/direct_sound_samples/crown_adtom4.bin"

    .align 2
crown_adtom5:
	.incbin "sound/direct_sound_samples/crown_adtom5.bin"

    .align 2
crown_adtom6:
	.incbin "sound/direct_sound_samples/crown_adtom6.bin"

    .align 2
crown_aflta4:
	.incbin "sound/direct_sound_samples/crown_aflta4.bin"

    .align 2
crown_afltc4:
	.incbin "sound/direct_sound_samples/crown_afltc4.bin"

    .align 2
crown_afltc6:
	.incbin "sound/direct_sound_samples/crown_afltc6.bin"

    .align 2
crown_afltf5:
	.incbin "sound/direct_sound_samples/crown_afltf5.bin"

    .align 2
crown_applause:
	.incbin "sound/direct_sound_samples/crown_applause.bin"

    .align 2
crown_asaxc5:
	.incbin "sound/direct_sound_samples/crown_asaxc5.bin"

    .align 2
crown_asaxe4:
	.incbin "sound/direct_sound_samples/crown_asaxe4.bin"

    .align 2
crown_asaxg3:
	.incbin "sound/direct_sound_samples/crown_asaxg3.bin"

    .align 2
crown_atkanac2:
	.incbin "sound/direct_sound_samples/crown_atkanac2.bin"

    .align 2
crown_bagpipeas2:
	.incbin "sound/direct_sound_samples/crown_bagpipeas2.bin"

    .align 2
crown_bagpipeas4:
	.incbin "sound/direct_sound_samples/crown_bagpipeas4.bin"

    .align 2
crown_bagpipeg5:
	.incbin "sound/direct_sound_samples/crown_bagpipeg5.bin"

    .align 2
crown_bangstc1:
	.incbin "sound/direct_sound_samples/crown_bangstc1.bin"

    .align 2
crown_bangstc2:
	.incbin "sound/direct_sound_samples/crown_bangstc2.bin"

    .align 2
crown_bangstc3:
	.incbin "sound/direct_sound_samples/crown_bangstc3.bin"

    .align 2
crown_banjoe3:
	.incbin "sound/direct_sound_samples/crown_banjoe3.bin"

    .align 2
crown_banjoe4:
	.incbin "sound/direct_sound_samples/crown_banjoe4.bin"

    .align 2
crown_bassna3:
	.incbin "sound/direct_sound_samples/crown_bassna3.bin"

    .align 2
crown_bassnc3:
	.incbin "sound/direct_sound_samples/crown_bassnc3.bin"

    .align 2
crown_bassne2:
	.incbin "sound/direct_sound_samples/crown_bassne2.bin"

    .align 2
crown_bassnf4:
	.incbin "sound/direct_sound_samples/crown_bassnf4.bin"

    .align 2
crown_bdownc2:
	.incbin "sound/direct_sound_samples/crown_bdownc2.bin"

    .align 2
crown_bdownc3:
	.incbin "sound/direct_sound_samples/crown_bdownc3.bin"

    .align 2
crown_bdownc4:
	.incbin "sound/direct_sound_samples/crown_bdownc4.bin"

    .align 2
crown_brushhit:
	.incbin "sound/direct_sound_samples/crown_brushhit.bin"

    .align 2
crown_brushrapid:
	.incbin "sound/direct_sound_samples/crown_brushrapid.bin"

    .align 2
crown_brushswirl:
	.incbin "sound/direct_sound_samples/crown_brushswirl.bin"

    .align 2
crown_bsaxb3:
	.incbin "sound/direct_sound_samples/crown_bsaxb3.bin"

    .align 2
crown_bsaxd3:
	.incbin "sound/direct_sound_samples/crown_bsaxd3.bin"

    .align 2
crown_bsaxf2:
	.incbin "sound/direct_sound_samples/crown_bsaxf2.bin"

    .align 2
crown_celestac4:
	.incbin "sound/direct_sound_samples/crown_celestac4.bin"

    .align 2
crown_celestac5:
	.incbin "sound/direct_sound_samples/crown_celestac5.bin"

    .align 2
crown_celestac6:
	.incbin "sound/direct_sound_samples/crown_celestac6.bin"

    .align 2
crown_celloc2:
	.incbin "sound/direct_sound_samples/crown_celloc2.bin"

    .align 2
crown_celloc3:
	.incbin "sound/direct_sound_samples/crown_celloc3.bin"

    .align 2
crown_celloc4:
	.incbin "sound/direct_sound_samples/crown_celloc4.bin"

    .align 2
crown_celloc5:
	.incbin "sound/direct_sound_samples/crown_celloc5.bin"

    .align 2
crown_chmchh:
	.incbin "sound/direct_sound_samples/crown_chmchh.bin"

    .align 2
crown_chmcrash:
	.incbin "sound/direct_sound_samples/crown_chmcrash.bin"

    .align 2
crown_chmkick:
	.incbin "sound/direct_sound_samples/crown_chmkick.bin"

    .align 2
crown_chmohh:
	.incbin "sound/direct_sound_samples/crown_chmohh.bin"

    .align 2
crown_chmride:
	.incbin "sound/direct_sound_samples/crown_chmride.bin"

    .align 2
crown_chmsnare:
	.incbin "sound/direct_sound_samples/crown_chmsnare.bin"

    .align 2
crown_chmtom1:
	.incbin "sound/direct_sound_samples/crown_chmtom1.bin"

    .align 2
crown_chmtom3:
	.incbin "sound/direct_sound_samples/crown_chmtom3.bin"

    .align 2
crown_choirc3:
	.incbin "sound/direct_sound_samples/crown_choirc3.bin"

    .align 2
crown_choirc4:
	.incbin "sound/direct_sound_samples/crown_choirc4.bin"

    .align 2
crown_choirc5:
	.incbin "sound/direct_sound_samples/crown_choirc5.bin"

    .align 2
crown_choirc6:
	.incbin "sound/direct_sound_samples/crown_choirc6.bin"

    .align 2
crown_clavc2:
	.incbin "sound/direct_sound_samples/crown_clavc2.bin"

    .align 2
crown_clavc3:
	.incbin "sound/direct_sound_samples/crown_clavc3.bin"

    .align 2
crown_clavc4:
	.incbin "sound/direct_sound_samples/crown_clavc4.bin"

    .align 2
crown_clavc5:
	.incbin "sound/direct_sound_samples/crown_clavc5.bin"

    .align 2
crown_clnstrc5:
	.incbin "sound/direct_sound_samples/crown_clnstrc5.bin"

    .align 2
crown_clnstre4:
	.incbin "sound/direct_sound_samples/crown_clnstre4.bin"

    .align 2
crown_clnstrg2:
	.incbin "sound/direct_sound_samples/crown_clnstrg2.bin"

    .align 2
crown_clnstrg3:
	.incbin "sound/direct_sound_samples/crown_clnstrg3.bin"

    .align 2
crown_cosmc2:
	.incbin "sound/direct_sound_samples/crown_cosmc2.bin"

    .align 2
crown_cosmc3:
	.incbin "sound/direct_sound_samples/crown_cosmc3.bin"

    .align 2
crown_cosmc4:
	.incbin "sound/direct_sound_samples/crown_cosmc4.bin"

    .align 2
crown_cosmc5:
	.incbin "sound/direct_sound_samples/crown_cosmc5.bin"

    .align 2
crown_cosmc6:
	.incbin "sound/direct_sound_samples/crown_cosmc6.bin"

    .align 2
crown_crysepc3:
	.incbin "sound/direct_sound_samples/crown_crysepc3.bin"

    .align 2
crown_crysepc4:
	.incbin "sound/direct_sound_samples/crown_crysepc4.bin"

    .align 2
crown_cuatroa4:
	.incbin "sound/direct_sound_samples/crown_cuatroa4.bin"

    .align 2
crown_cuatrod4:
	.incbin "sound/direct_sound_samples/crown_cuatrod4.bin"

    .align 2
crown_cuatroe5:
	.incbin "sound/direct_sound_samples/crown_cuatroe5.bin"

    .align 2
crown_cuatrog3:
	.incbin "sound/direct_sound_samples/crown_cuatrog3.bin"

    .align 2
crown_dighrpc3:
	.incbin "sound/direct_sound_samples/crown_dighrpc3.bin"

    .align 2
crown_dighrpc5:
	.incbin "sound/direct_sound_samples/crown_dighrpc5.bin"

    .align 2
crown_disgtslide:
	.incbin "sound/direct_sound_samples/crown_disgtslide.bin"

    .align 2
crown_disharmoc5:
	.incbin "sound/direct_sound_samples/crown_disharmoc5.bin"

    .align 2
crown_dulcimc3:
	.incbin "sound/direct_sound_samples/crown_dulcimc3.bin"

    .align 2
crown_dulcimc4:
	.incbin "sound/direct_sound_samples/crown_dulcimc4.bin"

    .align 2
crown_dulcimc5:
	.incbin "sound/direct_sound_samples/crown_dulcimc5.bin"

    .align 2
crown_dulcimc6:
	.incbin "sound/direct_sound_samples/crown_dulcimc6.bin"

    .align 2
crown_erhua4:
	.incbin "sound/direct_sound_samples/crown_erhua4.bin"

    .align 2
crown_erhua5:
	.incbin "sound/direct_sound_samples/crown_erhua5.bin"

    .align 2
crown_erhud4:
	.incbin "sound/direct_sound_samples/crown_erhud4.bin"

    .align 2
crown_erhue5:
	.incbin "sound/direct_sound_samples/crown_erhue5.bin"

    .align 2
crown_etherec5:
	.incbin "sound/direct_sound_samples/crown_etherec5.bin"

    .align 2
crown_fanbela5:
	.incbin "sound/direct_sound_samples/crown_fanbela5.bin"

    .align 2
crown_fanbelg4:
	.incbin "sound/direct_sound_samples/crown_fanbelg4.bin"

    .align 2
crown_fantasc5:
	.incbin "sound/direct_sound_samples/crown_fantasc5.bin"

    .align 2
crown_fantasg3:
	.incbin "sound/direct_sound_samples/crown_fantasg3.bin"

    .align 2
crown_fatbrassc3:
	.incbin "sound/direct_sound_samples/crown_fatbrassc3.bin"

    .align 2
crown_fatbrassc4:
	.incbin "sound/direct_sound_samples/crown_fatbrassc4.bin"

    .align 2
crown_fatbrassc5:
	.incbin "sound/direct_sound_samples/crown_fatbrassc5.bin"

    .align 2
crown_fatmonoc3:
	.incbin "sound/direct_sound_samples/crown_fatmonoc3.bin"

    .align 2
crown_fatmonoc4:
	.incbin "sound/direct_sound_samples/crown_fatmonoc4.bin"

    .align 2
crown_fatmonoc5:
	.incbin "sound/direct_sound_samples/crown_fatmonoc5.bin"

    .align 2
crown_fenbassc1:
	.incbin "sound/direct_sound_samples/crown_fenbassc1.bin"

    .align 2
crown_fenbassc2:
	.incbin "sound/direct_sound_samples/crown_fenbassc2.bin"

    .align 2
crown_fenbassc3:
	.incbin "sound/direct_sound_samples/crown_fenbassc3.bin"

    .align 2
crown_fhnsc3:
	.incbin "sound/direct_sound_samples/crown_fhnsc3.bin"

    .align 2
crown_fhnsc4:
	.incbin "sound/direct_sound_samples/crown_fhnsc4.bin"

    .align 2
crown_fhnsc5:
	.incbin "sound/direct_sound_samples/crown_fhnsc5.bin"

    .align 2
crown_fretlsc1:
	.incbin "sound/direct_sound_samples/crown_fretlsc1.bin"

    .align 2
crown_fretlsc2:
	.incbin "sound/direct_sound_samples/crown_fretlsc2.bin"

    .align 2
crown_fretlsc3:
	.incbin "sound/direct_sound_samples/crown_fretlsc3.bin"

    .align 2
crown_funkinc5:
	.incbin "sound/direct_sound_samples/crown_funkinc5.bin"

    .align 2
crown_funkine4:
	.incbin "sound/direct_sound_samples/crown_funkine4.bin"

    .align 2
crown_funking2:
	.incbin "sound/direct_sound_samples/crown_funking2.bin"

    .align 2
crown_funking3:
	.incbin "sound/direct_sound_samples/crown_funking3.bin"

    .align 2
crown_glockc5:
	.incbin "sound/direct_sound_samples/crown_glockc5.bin"

    .align 2
crown_glockc6:
	.incbin "sound/direct_sound_samples/crown_glockc6.bin"

    .align 2
crown_glockc7:
	.incbin "sound/direct_sound_samples/crown_glockc7.bin"

    .align 2
crown_haljazchina:
	.incbin "sound/direct_sound_samples/crown_haljazchina.bin"

    .align 2
crown_haljazkick:
	.incbin "sound/direct_sound_samples/crown_haljazkick.bin"

    .align 2
crown_haljazride:
	.incbin "sound/direct_sound_samples/crown_haljazride.bin"

    .align 2
crown_haljazsidestk:
	.incbin "sound/direct_sound_samples/crown_haljazsidestk.bin"

    .align 2
crown_haljazsnare:
	.incbin "sound/direct_sound_samples/crown_haljazsnare.bin"

    .align 2
crown_haljazsplash:
	.incbin "sound/direct_sound_samples/crown_haljazsplash.bin"

    .align 2
crown_haljaztom1:
	.incbin "sound/direct_sound_samples/crown_haljaztom1.bin"

    .align 2
crown_haljaztom3:
	.incbin "sound/direct_sound_samples/crown_haljaztom3.bin"

    .align 2
crown_haljaztom4:
	.incbin "sound/direct_sound_samples/crown_haljaztom4.bin"

    .align 2
crown_haljaztom6:
	.incbin "sound/direct_sound_samples/crown_haljaztom6.bin"

    .align 2
crown_harmona4:
	.incbin "sound/direct_sound_samples/crown_harmona4.bin"

    .align 2
crown_harmone4:
	.incbin "sound/direct_sound_samples/crown_harmone4.bin"

    .align 2
crown_harmone5:
	.incbin "sound/direct_sound_samples/crown_harmone5.bin"

    .align 2
crown_harpc3:
	.incbin "sound/direct_sound_samples/crown_harpc3.bin"

    .align 2
crown_harpc4:
	.incbin "sound/direct_sound_samples/crown_harpc4.bin"

    .align 2
crown_harpc5:
	.incbin "sound/direct_sound_samples/crown_harpc5.bin"

    .align 2
crown_harpsic2:
	.incbin "sound/direct_sound_samples/crown_harpsic2.bin"

    .align 2
crown_harpsic3:
	.incbin "sound/direct_sound_samples/crown_harpsic3.bin"

    .align 2
crown_harpsic4:
	.incbin "sound/direct_sound_samples/crown_harpsic4.bin"

    .align 2
crown_harpsic5:
	.incbin "sound/direct_sound_samples/crown_harpsic5.bin"

    .align 2
crown_harpsic6:
	.incbin "sound/direct_sound_samples/crown_harpsic6.bin"

    .align 2
crown_hsawc4:
	.incbin "sound/direct_sound_samples/crown_hsawc4.bin"

    .align 2
crown_hsawd5:
	.incbin "sound/direct_sound_samples/crown_hsawd5.bin"

    .align 2
crown_hsawe3:
	.incbin "sound/direct_sound_samples/crown_hsawe3.bin"

    .align 2
crown_hsawg4:
	.incbin "sound/direct_sound_samples/crown_hsawg4.bin"

    .align 2
crown_hslapc1:
	.incbin "sound/direct_sound_samples/crown_hslapc1.bin"

    .align 2
crown_hslapc2:
	.incbin "sound/direct_sound_samples/crown_hslapc2.bin"

    .align 2
crown_hslapc3:
	.incbin "sound/direct_sound_samples/crown_hslapc3.bin"

    .align 2
crown_jazgtc2:
	.incbin "sound/direct_sound_samples/crown_jazgtc2.bin"

    .align 2
crown_jazgtc3:
	.incbin "sound/direct_sound_samples/crown_jazgtc3.bin"

    .align 2
crown_jazgtc4:
	.incbin "sound/direct_sound_samples/crown_jazgtc4.bin"

    .align 2
crown_jazgtc5:
	.incbin "sound/direct_sound_samples/crown_jazgtc5.bin"

    .align 2
crown_kalimbae4:
	.incbin "sound/direct_sound_samples/crown_kalimbae4.bin"

    .align 2
crown_kalimbae5:
	.incbin "sound/direct_sound_samples/crown_kalimbae5.bin"

    .align 2
crown_kotoc4:
	.incbin "sound/direct_sound_samples/crown_kotoc4.bin"

    .align 2
crown_kotoc5:
	.incbin "sound/direct_sound_samples/crown_kotoc5.bin"

    .align 2
crown_kotog5:
	.incbin "sound/direct_sound_samples/crown_kotog5.bin"

    .align 2
crown_lizepb1:
	.incbin "sound/direct_sound_samples/crown_lizepb1.bin"

    .align 2
crown_lizepc4:
	.incbin "sound/direct_sound_samples/crown_lizepc4.bin"

    .align 2
crown_lizepc6:
	.incbin "sound/direct_sound_samples/crown_lizepc6.bin"

    .align 2
crown_lizepd3:
	.incbin "sound/direct_sound_samples/crown_lizepd3.bin"

    .align 2
crown_lizepd5:
	.incbin "sound/direct_sound_samples/crown_lizepd5.bin"

    .align 2
crown_m1crash:
	.incbin "sound/direct_sound_samples/crown_m1crash.bin"

    .align 2
crown_m1kick:
	.incbin "sound/direct_sound_samples/crown_m1kick.bin"

    .align 2
crown_m1snare:
	.incbin "sound/direct_sound_samples/crown_m1snare.bin"

    .align 2
crown_marimc3:
	.incbin "sound/direct_sound_samples/crown_marimc3.bin"

    .align 2
crown_marimc4:
	.incbin "sound/direct_sound_samples/crown_marimc4.bin"

    .align 2
crown_marimc5:
	.incbin "sound/direct_sound_samples/crown_marimc5.bin"

    .align 2
crown_marimg4:
	.incbin "sound/direct_sound_samples/crown_marimg4.bin"

    .align 2
crown_mrbrassc2:
	.incbin "sound/direct_sound_samples/crown_mrbrassc2.bin"

    .align 2
crown_mrbrassg3:
	.incbin "sound/direct_sound_samples/crown_mrbrassg3.bin"

    .align 2
crown_mtpta5:
	.incbin "sound/direct_sound_samples/crown_mtpta5.bin"

    .align 2
crown_mtptb4:
	.incbin "sound/direct_sound_samples/crown_mtptb4.bin"

    .align 2
crown_mtptd4:
	.incbin "sound/direct_sound_samples/crown_mtptd4.bin"

    .align 2
crown_musboxc3:
	.incbin "sound/direct_sound_samples/crown_musboxc3.bin"

    .align 2
crown_musboxc4:
	.incbin "sound/direct_sound_samples/crown_musboxc4.bin"

    .align 2
crown_musboxc5:
	.incbin "sound/direct_sound_samples/crown_musboxc5.bin"

    .align 2
crown_musboxc6:
	.incbin "sound/direct_sound_samples/crown_musboxc6.bin"

    .align 2
crown_nylonc5:
	.incbin "sound/direct_sound_samples/crown_nylonc5.bin"

    .align 2
crown_nylone4:
	.incbin "sound/direct_sound_samples/crown_nylone4.bin"

    .align 2
crown_nylong2:
	.incbin "sound/direct_sound_samples/crown_nylong2.bin"

    .align 2
crown_nylong3:
	.incbin "sound/direct_sound_samples/crown_nylong3.bin"

    .align 2
crown_nyslapa1:
	.incbin "sound/direct_sound_samples/crown_nyslapa1.bin"

    .align 2
crown_nyslapa2:
	.incbin "sound/direct_sound_samples/crown_nyslapa2.bin"

    .align 2
crown_nyslapc1:
	.incbin "sound/direct_sound_samples/crown_nyslapc1.bin"

    .align 2
crown_nyslapd2:
	.incbin "sound/direct_sound_samples/crown_nyslapd2.bin"

    .align 2
crown_nyslapd3:
	.incbin "sound/direct_sound_samples/crown_nyslapd3.bin"

    .align 2
crown_nyslaps1:
	.incbin "sound/direct_sound_samples/crown_nyslaps1.bin"

    .align 2
crown_nyslaps2:
	.incbin "sound/direct_sound_samples/crown_nyslaps2.bin"

    .align 2
crown_nyslaps3:
	.incbin "sound/direct_sound_samples/crown_nyslaps3.bin"

    .align 2
crown_nyslaps4:
	.incbin "sound/direct_sound_samples/crown_nyslaps4.bin"

    .align 2
crown_oboea5:
	.incbin "sound/direct_sound_samples/crown_oboea5.bin"

    .align 2
crown_oboec5:
	.incbin "sound/direct_sound_samples/crown_oboec5.bin"

    .align 2
crown_oboee4:
	.incbin "sound/direct_sound_samples/crown_oboee4.bin"

    .align 2
crown_okagogo:
	.incbin "sound/direct_sound_samples/crown_okagogo.bin"

    .align 2
crown_okbongo:
	.incbin "sound/direct_sound_samples/crown_okbongo.bin"

    .align 2
crown_okcasta:
	.incbin "sound/direct_sound_samples/crown_okcasta.bin"

    .align 2
crown_okclap:
	.incbin "sound/direct_sound_samples/crown_okclap.bin"

    .align 2
crown_okclave:
	.incbin "sound/direct_sound_samples/crown_okclave.bin"

    .align 2
crown_okconga:
	.incbin "sound/direct_sound_samples/crown_okconga.bin"

    .align 2
crown_okcongam:
	.incbin "sound/direct_sound_samples/crown_okcongam.bin"

    .align 2
crown_okgong:
	.incbin "sound/direct_sound_samples/crown_okgong.bin"

    .align 2
crown_okguiro:
	.incbin "sound/direct_sound_samples/crown_okguiro.bin"

    .align 2
crown_okride:
	.incbin "sound/direct_sound_samples/crown_okride.bin"

    .align 2
crown_okshakr1:
	.incbin "sound/direct_sound_samples/crown_okshakr1.bin"

    .align 2
crown_okshakr2:
	.incbin "sound/direct_sound_samples/crown_okshakr2.bin"

    .align 2
crown_oksnare:
	.incbin "sound/direct_sound_samples/crown_oksnare.bin"

    .align 2
crown_oktabla1:
	.incbin "sound/direct_sound_samples/crown_oktabla1.bin"

    .align 2
crown_oktabla2:
	.incbin "sound/direct_sound_samples/crown_oktabla2.bin"

    .align 2
crown_oktambo:
	.incbin "sound/direct_sound_samples/crown_oktambo.bin"

    .align 2
crown_oktrim:
	.incbin "sound/direct_sound_samples/crown_oktrim.bin"

    .align 2
crown_oktrio:
	.incbin "sound/direct_sound_samples/crown_oktrio.bin"

    .align 2
crown_okwblock:
	.incbin "sound/direct_sound_samples/crown_okwblock.bin"

    .align 2
crown_oliverchh:
	.incbin "sound/direct_sound_samples/crown_oliverchh.bin"

    .align 2
crown_oliverkick:
	.incbin "sound/direct_sound_samples/crown_oliverkick.bin"

    .align 2
crown_oliverohh:
	.incbin "sound/direct_sound_samples/crown_oliverohh.bin"

    .align 2
crown_oliverphh:
	.incbin "sound/direct_sound_samples/crown_oliverphh.bin"

    .align 2
crown_oliversnare:
	.incbin "sound/direct_sound_samples/crown_oliversnare.bin"

    .align 2
crown_olivertom:
	.incbin "sound/direct_sound_samples/crown_olivertom.bin"

    .align 2
crown_orchbd1:
	.incbin "sound/direct_sound_samples/crown_orchbd1.bin"

    .align 2
crown_orchbd2:
	.incbin "sound/direct_sound_samples/crown_orchbd2.bin"

    .align 2
crown_orchcrash1:
	.incbin "sound/direct_sound_samples/crown_orchcrash1.bin"

    .align 2
crown_orchcymcl1:
	.incbin "sound/direct_sound_samples/crown_orchcymcl1.bin"

    .align 2
crown_orchcymcl2:
	.incbin "sound/direct_sound_samples/crown_orchcymcl2.bin"

    .align 2
crown_orchitg4:
	.incbin "sound/direct_sound_samples/crown_orchitg4.bin"

    .align 2
crown_orchsnr2:
	.incbin "sound/direct_sound_samples/crown_orchsnr2.bin"

    .align 2
crown_orchsnrside:
	.incbin "sound/direct_sound_samples/crown_orchsnrside.bin"

    .align 2
crown_ostrc2:
	.incbin "sound/direct_sound_samples/crown_ostrc2.bin"

    .align 2
crown_ostrc3:
	.incbin "sound/direct_sound_samples/crown_ostrc3.bin"

    .align 2
crown_ostrc4:
	.incbin "sound/direct_sound_samples/crown_ostrc4.bin"

    .align 2
crown_ostrc5:
	.incbin "sound/direct_sound_samples/crown_ostrc5.bin"

    .align 2
crown_ostrc6:
	.incbin "sound/direct_sound_samples/crown_ostrc6.bin"

    .align 2
crown_p5orgc3:
	.incbin "sound/direct_sound_samples/crown_p5orgc3.bin"

    .align 2
crown_p5orgc5:
	.incbin "sound/direct_sound_samples/crown_p5orgc5.bin"

    .align 2
crown_paccorc3:
	.incbin "sound/direct_sound_samples/crown_paccorc3.bin"

    .align 2
crown_paccorc4:
	.incbin "sound/direct_sound_samples/crown_paccorc4.bin"

    .align 2
crown_paccorc5:
	.incbin "sound/direct_sound_samples/crown_paccorc5.bin"

    .align 2
crown_panflc4:
	.incbin "sound/direct_sound_samples/crown_panflc4.bin"

    .align 2
crown_panflc5:
	.incbin "sound/direct_sound_samples/crown_panflc5.bin"

    .align 2
crown_panflc6:
	.incbin "sound/direct_sound_samples/crown_panflc6.bin"

    .align 2
crown_pdiste2:
	.incbin "sound/direct_sound_samples/crown_pdiste2.bin"

    .align 2
crown_pdiste3:
	.incbin "sound/direct_sound_samples/crown_pdiste3.bin"

    .align 2
crown_pdiste4:
	.incbin "sound/direct_sound_samples/crown_pdiste4.bin"

    .align 2
crown_pdiste5:
	.incbin "sound/direct_sound_samples/crown_pdiste5.bin"

    .align 2
crown_perkysc4:
	.incbin "sound/direct_sound_samples/crown_perkysc4.bin"

    .align 2
crown_phatkick:
	.incbin "sound/direct_sound_samples/crown_phatkick.bin"

    .align 2
crown_phatsnare:
	.incbin "sound/direct_sound_samples/crown_phatsnare.bin"

    .align 2
crown_pianofc1:
	.incbin "sound/direct_sound_samples/crown_pianofc1.bin"

    .align 2
crown_pianofc2:
	.incbin "sound/direct_sound_samples/crown_pianofc2.bin"

    .align 2
crown_pianofc3:
	.incbin "sound/direct_sound_samples/crown_pianofc3.bin"

    .align 2
crown_pianofc4:
	.incbin "sound/direct_sound_samples/crown_pianofc4.bin"

    .align 2
crown_pianofc5:
	.incbin "sound/direct_sound_samples/crown_pianofc5.bin"

    .align 2
crown_pianofc6:
	.incbin "sound/direct_sound_samples/crown_pianofc6.bin"

    .align 2
crown_pianofc7:
	.incbin "sound/direct_sound_samples/crown_pianofc7.bin"

    .align 2
crown_pianopc1:
	.incbin "sound/direct_sound_samples/crown_pianopc1.bin"

    .align 2
crown_pianopc2:
	.incbin "sound/direct_sound_samples/crown_pianopc2.bin"

    .align 2
crown_pianopc3:
	.incbin "sound/direct_sound_samples/crown_pianopc3.bin"

    .align 2
crown_pianopc4:
	.incbin "sound/direct_sound_samples/crown_pianopc4.bin"

    .align 2
crown_pianopc5:
	.incbin "sound/direct_sound_samples/crown_pianopc5.bin"

    .align 2
crown_pianopc6:
	.incbin "sound/direct_sound_samples/crown_pianopc6.bin"

    .align 2
crown_pianopc7:
	.incbin "sound/direct_sound_samples/crown_pianopc7.bin"

    .align 2
crown_piccoc7:
	.incbin "sound/direct_sound_samples/crown_piccoc7.bin"

    .align 2
crown_piccoe6:
	.incbin "sound/direct_sound_samples/crown_piccoe6.bin"

    .align 2
crown_piccog5:
	.incbin "sound/direct_sound_samples/crown_piccog5.bin"

    .align 2
crown_pizzc2:
	.incbin "sound/direct_sound_samples/crown_pizzc2.bin"

    .align 2
crown_pizzc3:
	.incbin "sound/direct_sound_samples/crown_pizzc3.bin"

    .align 2
crown_pizzc4:
	.incbin "sound/direct_sound_samples/crown_pizzc4.bin"

    .align 2
crown_pizzc5:
	.incbin "sound/direct_sound_samples/crown_pizzc5.bin"

    .align 2
crown_pizzc6:
	.incbin "sound/direct_sound_samples/crown_pizzc6.bin"

    .align 2
crown_pmutee2:
	.incbin "sound/direct_sound_samples/crown_pmutee2.bin"

    .align 2
crown_pmutee3:
	.incbin "sound/direct_sound_samples/crown_pmutee3.bin"

    .align 2
crown_pmutee4:
	.incbin "sound/direct_sound_samples/crown_pmutee4.bin"

    .align 2
crown_pmutee5:
	.incbin "sound/direct_sound_samples/crown_pmutee5.bin"

    .align 2
crown_porga4:
	.incbin "sound/direct_sound_samples/crown_porga4.bin"

    .align 2
crown_porgc4:
	.incbin "sound/direct_sound_samples/crown_porgc4.bin"

    .align 2
crown_porge3:
	.incbin "sound/direct_sound_samples/crown_porge3.bin"

    .align 2
crown_porgf5:
	.incbin "sound/direct_sound_samples/crown_porgf5.bin"

    .align 2
crown_porgg2:
	.incbin "sound/direct_sound_samples/crown_porgg2.bin"

    .align 2
crown_powere2:
	.incbin "sound/direct_sound_samples/crown_powere2.bin"

    .align 2
crown_powere3:
	.incbin "sound/direct_sound_samples/crown_powere3.bin"

    .align 2
crown_psyepc3:
	.incbin "sound/direct_sound_samples/crown_psyepc3.bin"

    .align 2
crown_psyepc4:
	.incbin "sound/direct_sound_samples/crown_psyepc4.bin"

    .align 2
crown_psyepc5:
	.incbin "sound/direct_sound_samples/crown_psyepc5.bin"

    .align 2
crown_revcymc3:
	.incbin "sound/direct_sound_samples/crown_revcymc3.bin"

    .align 2
crown_rickenc2:
	.incbin "sound/direct_sound_samples/crown_rickenc2.bin"

    .align 2
crown_rickenc3:
	.incbin "sound/direct_sound_samples/crown_rickenc3.bin"

    .align 2
crown_rickenc4:
	.incbin "sound/direct_sound_samples/crown_rickenc4.bin"

    .align 2
crown_rocorgc3:
	.incbin "sound/direct_sound_samples/crown_rocorgc3.bin"

    .align 2
crown_rocorgc4:
	.incbin "sound/direct_sound_samples/crown_rocorgc4.bin"

    .align 2
crown_rocorgc5:
	.incbin "sound/direct_sound_samples/crown_rocorgc5.bin"

    .align 2
crown_rocorgc6:
	.incbin "sound/direct_sound_samples/crown_rocorgc6.bin"

    .align 2
crown_sc55tpta5:
	.incbin "sound/direct_sound_samples/crown_sc55tpta5.bin"

    .align 2
crown_sc55tptb4:
	.incbin "sound/direct_sound_samples/crown_sc55tptb4.bin"

    .align 2
crown_sc55tptd4:
	.incbin "sound/direct_sound_samples/crown_sc55tptd4.bin"

    .align 2
crown_sc88chh:
	.incbin "sound/direct_sound_samples/crown_sc88chh.bin"

    .align 2
crown_sc88china:
	.incbin "sound/direct_sound_samples/crown_sc88china.bin"

    .align 2
crown_sc88clap:
	.incbin "sound/direct_sound_samples/crown_sc88clap.bin"

    .align 2
crown_sc88crash:
	.incbin "sound/direct_sound_samples/crown_sc88crash.bin"

    .align 2
crown_sc88ohh:
	.incbin "sound/direct_sound_samples/crown_sc88ohh.bin"

    .align 2
crown_sc88phh:
	.incbin "sound/direct_sound_samples/crown_sc88phh.bin"

    .align 2
crown_sc88rbel:
	.incbin "sound/direct_sound_samples/crown_sc88rbel.bin"

    .align 2
crown_sc88ride:
	.incbin "sound/direct_sound_samples/crown_sc88ride.bin"

    .align 2
crown_sc88snare:
	.incbin "sound/direct_sound_samples/crown_sc88snare.bin"

    .align 2
crown_sc88splash:
	.incbin "sound/direct_sound_samples/crown_sc88splash.bin"

    .align 2
crown_sc88tom3:
	.incbin "sound/direct_sound_samples/crown_sc88tom3.bin"

    .align 2
crown_sctimpd3:
	.incbin "sound/direct_sound_samples/crown_sctimpd3.bin"

    .align 2
crown_sd20china:
	.incbin "sound/direct_sound_samples/crown_sd20china.bin"

    .align 2
crown_sd20kick:
	.incbin "sound/direct_sound_samples/crown_sd20kick.bin"

    .align 2
crown_sd20sleigh:
	.incbin "sound/direct_sound_samples/crown_sd20sleigh.bin"

    .align 2
crown_sd20snare:
	.incbin "sound/direct_sound_samples/crown_sd20snare.bin"

    .align 2
crown_sd20splash:
	.incbin "sound/direct_sound_samples/crown_sd20splash.bin"

    .align 2
crown_sd20tamb:
	.incbin "sound/direct_sound_samples/crown_sd20tamb.bin"

    .align 2
crown_seashore:
	.incbin "sound/direct_sound_samples/crown_seashore.bin"

    .align 2
crown_shakuc4:
	.incbin "sound/direct_sound_samples/crown_shakuc4.bin"

    .align 2
crown_shakuc5:
	.incbin "sound/direct_sound_samples/crown_shakuc5.bin"

    .align 2
crown_shakufx:
	.incbin "sound/direct_sound_samples/crown_shakufx.bin"

    .align 2
crown_shakug4:
	.incbin "sound/direct_sound_samples/crown_shakug4.bin"

    .align 2
crown_shakug5:
	.incbin "sound/direct_sound_samples/crown_shakug5.bin"

    .align 2
crown_shamic3:
	.incbin "sound/direct_sound_samples/crown_shamic3.bin"

    .align 2
crown_shamic4:
	.incbin "sound/direct_sound_samples/crown_shamic4.bin"

    .align 2
crown_shamig4:
	.incbin "sound/direct_sound_samples/crown_shamig4.bin"

    .align 2
crown_shoutbass:
	.incbin "sound/direct_sound_samples/crown_shoutbass.bin"

    .align 2
crown_sitara3:
	.incbin "sound/direct_sound_samples/crown_sitara3.bin"

    .align 2
crown_sitarb4:
	.incbin "sound/direct_sound_samples/crown_sitarb4.bin"

    .align 2
crown_spicce2:
	.incbin "sound/direct_sound_samples/crown_spicce2.bin"

    .align 2
crown_srxorccym:
	.incbin "sound/direct_sound_samples/crown_srxorccym.bin"

    .align 2
crown_srxrevcym:
	.incbin "sound/direct_sound_samples/crown_srxrevcym.bin"

    .align 2
crown_srxsnare:
	.incbin "sound/direct_sound_samples/crown_srxsnare.bin"

    .align 2
crown_srxsnroll:
	.incbin "sound/direct_sound_samples/crown_srxsnroll.bin"

    .align 2
crown_srxtimroll:
	.incbin "sound/direct_sound_samples/crown_srxtimroll.bin"

    .align 2
crown_ssawzg3:
	.incbin "sound/direct_sound_samples/crown_ssawzg3.bin"

    .align 2
crown_ssawzg4:
	.incbin "sound/direct_sound_samples/crown_ssawzg4.bin"

    .align 2
crown_ssawzg5:
	.incbin "sound/direct_sound_samples/crown_ssawzg5.bin"

    .align 2
crown_ssaxb4:
	.incbin "sound/direct_sound_samples/crown_ssaxb4.bin"

    .align 2
crown_ssaxd4:
	.incbin "sound/direct_sound_samples/crown_ssaxd4.bin"

    .align 2
crown_ssaxg5:
	.incbin "sound/direct_sound_samples/crown_ssaxg5.bin"

    .align 2
crown_steelc5:
	.incbin "sound/direct_sound_samples/crown_steelc5.bin"

    .align 2
crown_steele4:
	.incbin "sound/direct_sound_samples/crown_steele4.bin"

    .align 2
crown_steelg2:
	.incbin "sound/direct_sound_samples/crown_steelg2.bin"

    .align 2
crown_steelg3:
	.incbin "sound/direct_sound_samples/crown_steelg3.bin"

    .align 2
crown_steelk1:
	.incbin "sound/direct_sound_samples/crown_steelk1.bin"

    .align 2
crown_steelk2:
	.incbin "sound/direct_sound_samples/crown_steelk2.bin"

    .align 2
crown_steelk3:
	.incbin "sound/direct_sound_samples/crown_steelk3.bin"

    .align 2
crown_steelrc5:
	.incbin "sound/direct_sound_samples/crown_steelrc5.bin"

    .align 2
crown_steelre4:
	.incbin "sound/direct_sound_samples/crown_steelre4.bin"

    .align 2
crown_steelrg2:
	.incbin "sound/direct_sound_samples/crown_steelrg2.bin"

    .align 2
crown_steelrg3:
	.incbin "sound/direct_sound_samples/crown_steelrg3.bin"

    .align 2
crown_stlpana3:
	.incbin "sound/direct_sound_samples/crown_stlpana3.bin"

    .align 2
crown_stlpanb4:
	.incbin "sound/direct_sound_samples/crown_stlpanb4.bin"

    .align 2
crown_strensc2:
	.incbin "sound/direct_sound_samples/crown_strensc2.bin"

    .align 2
crown_strensc3:
	.incbin "sound/direct_sound_samples/crown_strensc3.bin"

    .align 2
crown_strensc4:
	.incbin "sound/direct_sound_samples/crown_strensc4.bin"

    .align 2
crown_strensc5:
	.incbin "sound/direct_sound_samples/crown_strensc5.bin"

    .align 2
crown_strensc6:
	.incbin "sound/direct_sound_samples/crown_strensc6.bin"

    .align 2
crown_sword:
	.incbin "sound/direct_sound_samples/crown_sword.bin"

    .align 2
crown_synstrc2:
	.incbin "sound/direct_sound_samples/crown_synstrc2.bin"

    .align 2
crown_synstrc3:
	.incbin "sound/direct_sound_samples/crown_synstrc3.bin"

    .align 2
crown_synstrc4:
	.incbin "sound/direct_sound_samples/crown_synstrc4.bin"

    .align 2
crown_synstrc5:
	.incbin "sound/direct_sound_samples/crown_synstrc5.bin"

    .align 2
crown_t9crash:
	.incbin "sound/direct_sound_samples/crown_t9crash.bin"

    .align 2
crown_t9kick:
	.incbin "sound/direct_sound_samples/crown_t9kick.bin"

    .align 2
crown_t9sfx:
	.incbin "sound/direct_sound_samples/crown_t9sfx.bin"

    .align 2
crown_t9snare:
	.incbin "sound/direct_sound_samples/crown_t9snare.bin"

    .align 2
crown_tbellc4:
	.incbin "sound/direct_sound_samples/crown_tbellc4.bin"

    .align 2
crown_tbellc5:
	.incbin "sound/direct_sound_samples/crown_tbellc5.bin"

    .align 2
crown_tbellg4:
	.incbin "sound/direct_sound_samples/crown_tbellg4.bin"

    .align 2
crown_timpc2:
	.incbin "sound/direct_sound_samples/crown_timpc2.bin"

    .align 2
crown_timpc3:
	.incbin "sound/direct_sound_samples/crown_timpc3.bin"

    .align 2
crown_tpta5:
	.incbin "sound/direct_sound_samples/crown_tpta5.bin"

    .align 2
crown_tptb4:
	.incbin "sound/direct_sound_samples/crown_tptb4.bin"

    .align 2
crown_tptd4:
	.incbin "sound/direct_sound_samples/crown_tptd4.bin"

    .align 2
crown_tremstrc2:
	.incbin "sound/direct_sound_samples/crown_tremstrc2.bin"

    .align 2
crown_tremstrc3:
	.incbin "sound/direct_sound_samples/crown_tremstrc3.bin"

    .align 2
crown_tremstrc4:
	.incbin "sound/direct_sound_samples/crown_tremstrc4.bin"

    .align 2
crown_tremstrc5:
	.incbin "sound/direct_sound_samples/crown_tremstrc5.bin"

    .align 2
crown_tremstrc6:
	.incbin "sound/direct_sound_samples/crown_tremstrc6.bin"

    .align 2
crown_tripnoc2:
	.incbin "sound/direct_sound_samples/crown_tripnoc2.bin"

    .align 2
crown_tripnoc3:
	.incbin "sound/direct_sound_samples/crown_tripnoc3.bin"

    .align 2
crown_tripnoc4:
	.incbin "sound/direct_sound_samples/crown_tripnoc4.bin"

    .align 2
crown_tripnoc5:
	.incbin "sound/direct_sound_samples/crown_tripnoc5.bin"

    .align 2
crown_tripnoc6:
	.incbin "sound/direct_sound_samples/crown_tripnoc6.bin"

    .align 2
crown_tromc3:
	.incbin "sound/direct_sound_samples/crown_tromc3.bin"

    .align 2
crown_tromc4:
	.incbin "sound/direct_sound_samples/crown_tromc4.bin"

    .align 2
crown_tromc5:
	.incbin "sound/direct_sound_samples/crown_tromc5.bin"

    .align 2
crown_tsaxb3:
	.incbin "sound/direct_sound_samples/crown_tsaxb3.bin"

    .align 2
crown_tsaxd3:
	.incbin "sound/direct_sound_samples/crown_tsaxd3.bin"

    .align 2
crown_tsaxg4:
	.incbin "sound/direct_sound_samples/crown_tsaxg4.bin"

    .align 2
crown_ttstaccs2:
	.incbin "sound/direct_sound_samples/crown_ttstaccs2.bin"

    .align 2
crown_tubac1:
	.incbin "sound/direct_sound_samples/crown_tubac1.bin"

    .align 2
crown_tubac2:
	.incbin "sound/direct_sound_samples/crown_tubac2.bin"

    .align 2
crown_tubac3:
	.incbin "sound/direct_sound_samples/crown_tubac3.bin"

    .align 2
crown_ueberkick:
	.incbin "sound/direct_sound_samples/crown_ueberkick.bin"

    .align 2
crown_uprigrcn1:
	.incbin "sound/direct_sound_samples/crown_uprigrc-1.bin"

    .align 2
crown_uprigrc3:
	.incbin "sound/direct_sound_samples/crown_uprigrc3.bin"

    .align 2
crown_uprigrc4:
	.incbin "sound/direct_sound_samples/crown_uprigrc4.bin"

    .align 2
crown_uprigrcsn1:
	.incbin "sound/direct_sound_samples/crown_uprigrcs-1.bin"

    .align 2
crown_uprigre2:
	.incbin "sound/direct_sound_samples/crown_uprigre2.bin"

    .align 2
crown_vibrc4:
	.incbin "sound/direct_sound_samples/crown_vibrc4.bin"

    .align 2
crown_vibrc5:
	.incbin "sound/direct_sound_samples/crown_vibrc5.bin"

    .align 2
crown_vibrc6:
	.incbin "sound/direct_sound_samples/crown_vibrc6.bin"

    .align 2
crown_violac3:
	.incbin "sound/direct_sound_samples/crown_violac3.bin"

    .align 2
crown_violac4:
	.incbin "sound/direct_sound_samples/crown_violac4.bin"

    .align 2
crown_violac5:
	.incbin "sound/direct_sound_samples/crown_violac5.bin"

    .align 2
crown_violac6:
	.incbin "sound/direct_sound_samples/crown_violac6.bin"

    .align 2
crown_violinc4:
	.incbin "sound/direct_sound_samples/crown_violinc4.bin"

    .align 2
crown_violinc5:
	.incbin "sound/direct_sound_samples/crown_violinc5.bin"

    .align 2
crown_violinc6:
	.incbin "sound/direct_sound_samples/crown_violinc6.bin"

    .align 2
crown_voohc4:
	.incbin "sound/direct_sound_samples/crown_voohc4.bin"

    .align 2
crown_voohc5:
	.incbin "sound/direct_sound_samples/crown_voohc5.bin"

    .align 2
crown_voohg4:
	.incbin "sound/direct_sound_samples/crown_voohg4.bin"

    .align 2
crown_whistlc5:
	.incbin "sound/direct_sound_samples/crown_whistlc5.bin"

    .align 2
crown_whistlc6:
	.incbin "sound/direct_sound_samples/crown_whistlc6.bin"

    .align 2
crown_wind:
	.incbin "sound/direct_sound_samples/crown_wind.bin"

    .align 2
crown_xyloc5:
	.incbin "sound/direct_sound_samples/crown_xyloc5.bin"

    .align 2
crown_xyloc6:
	.incbin "sound/direct_sound_samples/crown_xyloc6.bin"

    .align 2
crown_xyloc7:
	.incbin "sound/direct_sound_samples/crown_xyloc7.bin"
