	.align 2
DirectSoundWaveData_08501508::
	.incbin "sound/direct_sound_samples/08501508.bin"

	.align 2
DirectSoundWaveData_08501BAC::
	.incbin "sound/direct_sound_samples/08501BAC.bin"

	.align 2
DirectSoundWaveData_085023A4::
	.incbin "sound/direct_sound_samples/085023A4.bin"

	.align 2
DirectSoundWaveData_08502F70::
	.incbin "sound/direct_sound_samples/08502F70.bin"

	.align 2
DirectSoundWaveData_08503EA8::
	.incbin "sound/direct_sound_samples/08503EA8.bin"

	.align 2
DirectSoundWaveData_08504B1C::
	.incbin "sound/direct_sound_samples/08504B1C.bin"

	.align 2
DirectSoundWaveData_08505FEC::
	.incbin "sound/direct_sound_samples/08505FEC.bin"

	.align 2
DirectSoundWaveData_0850769C::
	.incbin "sound/direct_sound_samples/0850769C.bin"

	.align 2
DirectSoundWaveData_085089E0::
	.incbin "sound/direct_sound_samples/085089E0.bin"

	.align 2
DirectSoundWaveData_08509484::
	.incbin "sound/direct_sound_samples/08509484.bin"

	.align 2
DirectSoundWaveData_0850A798::
	.incbin "sound/direct_sound_samples/0850A798.bin"

	.align 2
DirectSoundWaveData_0850DD94::
	.incbin "sound/direct_sound_samples/0850DD94.bin"

	.align 2
DirectSoundWaveData_0850E26C::
	.incbin "sound/direct_sound_samples/0850E26C.bin"

	.align 2
DirectSoundWaveData_0850FB48::
	.incbin "sound/direct_sound_samples/0850FB48.bin"

	.align 2
DirectSoundWaveData_08510E70::
	.incbin "sound/direct_sound_samples/08510E70.bin"

	.align 2
DirectSoundWaveData_08511310::
	.incbin "sound/direct_sound_samples/08511310.bin"

	.align 2
DirectSoundWaveData_08511A04::
	.incbin "sound/direct_sound_samples/08511A04.bin"

	.align 2
DirectSoundWaveData_08512294::
	.incbin "sound/direct_sound_samples/08512294.bin"

	.align 2
DirectSoundWaveData_08512B0C::
	.incbin "sound/direct_sound_samples/08512B0C.bin"

	.align 2
DirectSoundWaveData_08513B4C::
	.incbin "sound/direct_sound_samples/08513B4C.bin"

	.align 2
DirectSoundWaveData_08513F60::
	.incbin "sound/direct_sound_samples/08513F60.bin"

	.align 2
DirectSoundWaveData_08514D90::
	.incbin "sound/direct_sound_samples/08514D90.bin"

	.align 2
DirectSoundWaveData_08515D24::
	.incbin "sound/direct_sound_samples/08515D24.bin"

	.align 2
DirectSoundWaveData_085165D8::
	.incbin "sound/direct_sound_samples/085165D8.bin"

	.align 2
DirectSoundWaveData_08516EBC::
	.incbin "sound/direct_sound_samples/08516EBC.bin"

	.align 2
DirectSoundWaveData_08517DE8::
	.incbin "sound/direct_sound_samples/08517DE8.bin"

	.align 2
DirectSoundWaveData_08518300::
	.incbin "sound/direct_sound_samples/08518300.bin"

	.align 2
DirectSoundWaveData_085188C8::
	.incbin "sound/direct_sound_samples/085188C8.bin"

	.align 2
DirectSoundWaveData_085197E0::
	.incbin "sound/direct_sound_samples/085197E0.bin"

	.align 2
DirectSoundWaveData_0851B154::
	.incbin "sound/direct_sound_samples/0851B154.bin"

	.align 2
DirectSoundWaveData_0851D230::
	.incbin "sound/direct_sound_samples/0851D230.bin"

	.align 2
DirectSoundWaveData_08524A60::
	.incbin "sound/direct_sound_samples/08524A60.bin"

	.align 2
DirectSoundWaveData_08525418::
	.incbin "sound/direct_sound_samples/08525418.bin"

	.align 2
DirectSoundWaveData_08526298::
	.incbin "sound/direct_sound_samples/08526298.bin"

	.align 2
DirectSoundWaveData_0852710C::
	.incbin "sound/direct_sound_samples/0852710C.bin"

	.align 2
DirectSoundWaveData_08528920::
	.incbin "sound/direct_sound_samples/08528920.bin"

	.align 2
DirectSoundWaveData_08529EC4::
	.incbin "sound/direct_sound_samples/08529EC4.bin"

	.align 2
DirectSoundWaveData_0852B4A8::
	.incbin "sound/direct_sound_samples/0852B4A8.bin"

	.align 2
DirectSoundWaveData_0852C59C::
	.incbin "sound/direct_sound_samples/0852C59C.bin"

	.align 2
DirectSoundWaveData_0852CE94::
	.incbin "sound/direct_sound_samples/0852CE94.bin"

	.align 2
DirectSoundWaveData_0852DB6C::
	.incbin "sound/direct_sound_samples/0852DB6C.bin"

	.align 2
DirectSoundWaveData_0852EACC::
	.incbin "sound/direct_sound_samples/0852EACC.bin"

	.align 2
DirectSoundWaveData_0853012C::
	.incbin "sound/direct_sound_samples/0853012C.bin"

	.align 2
DirectSoundWaveData_08531688::
	.incbin "sound/direct_sound_samples/08531688.bin"

	.align 2
DirectSoundWaveData_08532214::
	.incbin "sound/direct_sound_samples/08532214.bin"

	.align 2
DirectSoundWaveData_085357B8::
	.incbin "sound/direct_sound_samples/085357B8.bin"

	.align 2
DirectSoundWaveData_08537AD4::
	.incbin "sound/direct_sound_samples/08537AD4.bin"

	.align 2
DirectSoundWaveData_0853B1A0::
	.incbin "sound/direct_sound_samples/0853B1A0.bin"

	.align 2
DirectSoundWaveData_0853C4F0::
	.incbin "sound/direct_sound_samples/0853C4F0.bin"

	.align 2
DirectSoundWaveData_0853DA00::
	.incbin "sound/direct_sound_samples/0853DA00.bin"

	.align 2
DirectSoundWaveData_0853EE20::
	.incbin "sound/direct_sound_samples/0853EE20.bin"

	.align 2
DirectSoundWaveData_0853FEBC::
	.incbin "sound/direct_sound_samples/0853FEBC.bin"

	.align 2
DirectSoundWaveData_08540F18::
	.incbin "sound/direct_sound_samples/08540F18.bin"

	.align 2
DirectSoundWaveData_08547EAC::
	.incbin "sound/direct_sound_samples/08547EAC.bin"

	.align 2
DirectSoundWaveData_0854C430::
	.incbin "sound/direct_sound_samples/0854C430.bin"

	.align 2
DirectSoundWaveData_0854E080::
	.incbin "sound/direct_sound_samples/0854E080.bin"

	.align 2
DirectSoundWaveData_0854EA8C::
	.incbin "sound/direct_sound_samples/0854EA8C.bin"

	.align 2
DirectSoundWaveData_085506A0::
	.incbin "sound/direct_sound_samples/085506A0.bin"

	.align 2
DirectSoundWaveData_08552000::
	.incbin "sound/direct_sound_samples/08552000.bin"

	.align 2
DirectSoundWaveData_085534C4::
	.incbin "sound/direct_sound_samples/085534C4.bin"

	.align 2
DirectSoundWaveData_08553C00::
	.incbin "sound/direct_sound_samples/08553C00.bin"

	.align 2
DirectSoundWaveData_085557F0::
	.incbin "sound/direct_sound_samples/085557F0.bin"

	.align 2
DirectSoundWaveData_08556BA4::
	.incbin "sound/direct_sound_samples/08556BA4.bin"

	.align 2
DirectSoundWaveData_08559228::
	.incbin "sound/direct_sound_samples/08559228.bin"

	.align 2
DirectSoundWaveData_0855A46C::
	.incbin "sound/direct_sound_samples/0855A46C.bin"

	.align 2
DirectSoundWaveData_0855B47C::
	.incbin "sound/direct_sound_samples/0855B47C.bin"

	.align 2
DirectSoundWaveData_0855C784::
	.incbin "sound/direct_sound_samples/0855C784.bin"

	.align 2
DirectSoundWaveData_0855E890::
	.incbin "sound/direct_sound_samples/0855E890.bin"

	.align 2
DirectSoundWaveData_0856086C::
	.incbin "sound/direct_sound_samples/0856086C.bin"

	.align 2
DirectSoundWaveData_08562A7C::
	.incbin "sound/direct_sound_samples/08562A7C.bin"

	.align 2
DirectSoundWaveData_08563248::
	.incbin "sound/direct_sound_samples/08563248.bin"

	.align 2
DirectSoundWaveData_08564BB8::
	.incbin "sound/direct_sound_samples/08564BB8.bin"

	.align 2
DirectSoundWaveData_08566B68::
	.incbin "sound/direct_sound_samples/08566B68.bin"

	.align 2
DirectSoundWaveData_08569E48::
	.incbin "sound/direct_sound_samples/08569E48.bin"

	.align 2
DirectSoundWaveData_0856A878::
	.incbin "sound/direct_sound_samples/0856A878.bin"

	.align 2
DirectSoundWaveData_0856B2AC::
	.incbin "sound/direct_sound_samples/0856B2AC.bin"

	.align 2
DirectSoundWaveData_0856CDEC::
	.incbin "sound/direct_sound_samples/0856CDEC.bin"

	.align 2
DirectSoundWaveData_0856D6B4::
	.incbin "sound/direct_sound_samples/0856D6B4.bin"

	.align 2
DirectSoundWaveData_0856EA84::
	.incbin "sound/direct_sound_samples/0856EA84.bin"

	.align 2
DirectSoundWaveData_085707C4::
	.incbin "sound/direct_sound_samples/085707C4.bin"

	.align 2
DirectSoundWaveData_08572734::
	.incbin "sound/direct_sound_samples/08572734.bin"

	.align 2
DirectSoundWaveData_085745A4::
	.incbin "sound/direct_sound_samples/085745A4.bin"

	.align 2
DirectSoundWaveData_08577594::
	.incbin "sound/direct_sound_samples/08577594.bin"

	.align 2
DirectSoundWaveData_0857A1E8::
	.incbin "sound/direct_sound_samples/0857A1E8.bin"

	.align 2
DirectSoundWaveData_0857CB30::
	.incbin "sound/direct_sound_samples/0857CB30.bin"

	.align 2
DirectSoundWaveData_0857E290::
	.incbin "sound/direct_sound_samples/0857E290.bin"

	.align 2
DirectSoundWaveData_0857E9F4::
	.incbin "sound/direct_sound_samples/0857E9F4.bin"

	.align 2
DirectSoundWaveData_0857FBF8::
	.incbin "sound/direct_sound_samples/0857FBF8.bin"

	.align 2
DirectSoundWaveData_08580EF8::
	.incbin "sound/direct_sound_samples/08580EF8.bin"

	.align 2
DirectSoundWaveData_08581C70::
	.incbin "sound/direct_sound_samples/08581C70.bin"

	.align 2
DirectSoundWaveData_085851E0::
	.incbin "sound/direct_sound_samples/085851E0.bin"

	.align 2
DirectSoundWaveData_08586640::
	.incbin "sound/direct_sound_samples/08586640.bin"

	.align 2
DirectSoundWaveData_08587150::
	.incbin "sound/direct_sound_samples/08587150.bin"

	.align 2
DirectSoundWaveData_085895F8::
	.incbin "sound/direct_sound_samples/085895F8.bin"

	.align 2
DirectSoundWaveData_0858B174::
	.incbin "sound/direct_sound_samples/0858B174.bin"

	.align 2
DirectSoundWaveData_0858B840::
	.incbin "sound/direct_sound_samples/0858B840.bin"

	.align 2
DirectSoundWaveData_0858CCC8::
	.incbin "sound/direct_sound_samples/0858CCC8.bin"

	.align 2
DirectSoundWaveData_0858D7E8::
	.incbin "sound/direct_sound_samples/0858D7E8.bin"

	.align 2
DirectSoundWaveData_0858E7C4::
	.incbin "sound/direct_sound_samples/0858E7C4.bin"

	.align 2
DirectSoundWaveData_0858FF68::
	.incbin "sound/direct_sound_samples/0858FF68.bin"

	.align 2
DirectSoundWaveData_08595410::
	.incbin "sound/direct_sound_samples/08595410.bin"

	.align 2
DirectSoundWaveData_08595EC0::
	.incbin "sound/direct_sound_samples/08595EC0.bin"

	.align 2
DirectSoundWaveData_08597244::
	.incbin "sound/direct_sound_samples/08597244.bin"

	.align 2
DirectSoundWaveData_08597890::
	.incbin "sound/direct_sound_samples/08597890.bin"

	.align 2
DirectSoundWaveData_085982AC::
	.incbin "sound/direct_sound_samples/085982AC.bin"

	.align 2
DirectSoundWaveData_0859D60C::
	.incbin "sound/direct_sound_samples/0859D60C.bin"

	.align 2
DirectSoundWaveData_085A54B0::
	.incbin "sound/direct_sound_samples/085A54B0.bin"

	.align 2
DirectSoundWaveData_085A64CC::
	.incbin "sound/direct_sound_samples/085A64CC.bin"

	.align 2
DirectSoundWaveData_085A7018::
	.incbin "sound/direct_sound_samples/085A7018.bin"

	.align 2
DirectSoundWaveData_085A7BB8::
	.incbin "sound/direct_sound_samples/085A7BB8.bin"

	.align 2
DirectSoundWaveData_085AB350::
	.incbin "sound/direct_sound_samples/085AB350.bin"

	.align 2
DirectSoundWaveData_085ADDF8::
	.incbin "sound/direct_sound_samples/085ADDF8.bin"

	.align 2
DirectSoundWaveData_085B2C08::
	.incbin "sound/direct_sound_samples/085B2C08.bin"

	.align 2
DirectSoundWaveData_085B48BC::
	.incbin "sound/direct_sound_samples/085B48BC.bin"

	.align 2
DirectSoundWaveData_085B76D8::
	.incbin "sound/direct_sound_samples/085B76D8.bin"

	.align 2
DirectSoundWaveData_085B89E0::
	.incbin "sound/direct_sound_samples/085B89E0.bin"

	.align 2
DirectSoundWaveData_085BBC08::
	.incbin "sound/direct_sound_samples/085BBC08.bin"

	.align 2
DirectSoundWaveData_085BE124::
	.incbin "sound/direct_sound_samples/085BE124.bin"

	.align 2
DirectSoundWaveData_085BFEB4::
	.incbin "sound/direct_sound_samples/085BFEB4.bin"

	.align 2
DirectSoundWaveData_085C2594::
	.incbin "sound/direct_sound_samples/085C2594.bin"

	.align 2
DirectSoundWaveData_085C4938::
	.incbin "sound/direct_sound_samples/085C4938.bin"

	.align 2
DirectSoundWaveData_085C51C8::
	.incbin "sound/direct_sound_samples/085C51C8.bin"

	.align 2
DirectSoundWaveData_085C5B8C::
	.incbin "sound/direct_sound_samples/085C5B8C.bin"

	.align 2
DirectSoundWaveData_085C6DAC::
	.incbin "sound/direct_sound_samples/085C6DAC.bin"

	.align 2
DirectSoundWaveData_085C9E38::
	.incbin "sound/direct_sound_samples/085C9E38.bin"

	.align 2
DirectSoundWaveData_085CB070::
	.incbin "sound/direct_sound_samples/085CB070.bin"

	.align 2
DirectSoundWaveData_085CBEC4::
	.incbin "sound/direct_sound_samples/085CBEC4.bin"

	.align 2
DirectSoundWaveData_085CE344::
	.incbin "sound/direct_sound_samples/085CE344.bin"

	.align 2
DirectSoundWaveData_085CFF40::
	.incbin "sound/direct_sound_samples/085CFF40.bin"

	.align 2
DirectSoundWaveData_085D1754::
	.incbin "sound/direct_sound_samples/085D1754.bin"

	.align 2
DirectSoundWaveData_085D3A20::
	.incbin "sound/direct_sound_samples/085D3A20.bin"

	.align 2
DirectSoundWaveData_085D5E60::
	.incbin "sound/direct_sound_samples/085D5E60.bin"

	.align 2
DirectSoundWaveData_085DB1F8::
	.incbin "sound/direct_sound_samples/085DB1F8.bin"

	.align 2
DirectSoundWaveData_085DF068::
	.incbin "sound/direct_sound_samples/085DF068.bin"

	.align 2
DirectSoundWaveData_085E0C78::
	.incbin "sound/direct_sound_samples/085E0C78.bin"

	.align 2
DirectSoundWaveData_085E2680::
	.incbin "sound/direct_sound_samples/085E2680.bin"

	.align 2
DirectSoundWaveData_085E5B08::
	.incbin "sound/direct_sound_samples/085E5B08.bin"

	.align 2
DirectSoundWaveData_085E8614::
	.incbin "sound/direct_sound_samples/085E8614.bin"

	.align 2
DirectSoundWaveData_085ED8A8::
	.incbin "sound/direct_sound_samples/085ED8A8.bin"

	.align 2
DirectSoundWaveData_085EFDEC::
	.incbin "sound/direct_sound_samples/085EFDEC.bin"

	.align 2
DirectSoundWaveData_085F2E90::
	.incbin "sound/direct_sound_samples/085F2E90.bin"

	.align 2
DirectSoundWaveData_085F4C1C::
	.incbin "sound/direct_sound_samples/085F4C1C.bin"

	.align 2
DirectSoundWaveData_085F87F4::
	.incbin "sound/direct_sound_samples/085F87F4.bin"

	.align 2
DirectSoundWaveData_085FAE5C::
	.incbin "sound/direct_sound_samples/085FAE5C.bin"

	.align 2
DirectSoundWaveData_085FBFCC::
	.incbin "sound/direct_sound_samples/085FBFCC.bin"

	.align 2
DirectSoundWaveData_085FD804::
	.incbin "sound/direct_sound_samples/085FD804.bin"

	.align 2
DirectSoundWaveData_085FF088::
	.incbin "sound/direct_sound_samples/085FF088.bin"
