	.align 4
ProgrammableWaveData_86B4830:: @ 86B4830
	.incbin "sound/programmable_wave_samples/86B4830.pcm"

ProgrammableWaveData_86B4840:: @ 86B4840
	.incbin "sound/programmable_wave_samples/86B4840.pcm"

ProgrammableWaveData_86B4850:: @ 86B4850
	.incbin "sound/programmable_wave_samples/86B4850.pcm"

ProgrammableWaveData_86B4860:: @ 86B4860
	.incbin "sound/programmable_wave_samples/86B4860.pcm"

ProgrammableWaveData_86B4870:: @ 86B4870
	.incbin "sound/programmable_wave_samples/86B4870.pcm"

ProgrammableWaveData_86B4880:: @ 86B4880
	.incbin "sound/programmable_wave_samples/86B4880.pcm"

ProgrammableWaveData_86B4890:: @ 86B4890
	.incbin "sound/programmable_wave_samples/86B4890.pcm"

ProgrammableWaveData_86B48A0:: @ 86B48A0
	.incbin "sound/programmable_wave_samples/86B48A0.pcm"

ProgrammableWaveData_86B48B0:: @ 86B48B0
	.incbin "sound/programmable_wave_samples/86B48B0.pcm"

ProgrammableWaveData_86B48C0:: @ 86B48C0
	.incbin "sound/programmable_wave_samples/86B48C0.pcm"

ProgrammableWaveData_86B48D0:: @ 86B48D0
	.incbin "sound/programmable_wave_samples/86B48D0.pcm"

ProgrammableWaveData_86B48E0:: @ 86B48E0
	.incbin "sound/programmable_wave_samples/86B48E0.pcm"

ProgrammableWaveData_86B48F0:: @ 86B48F0
	.incbin "sound/programmable_wave_samples/86B48F0.pcm"

ProgrammableWaveData_86B4900:: @ 86B4900
	.incbin "sound/programmable_wave_samples/86B4900.pcm"

ProgrammableWaveData_86B4910:: @ 86B4910
	.incbin "sound/programmable_wave_samples/86B4910.pcm"

ProgrammableWaveData_86B4920:: @ 86B4920
	.incbin "sound/programmable_wave_samples/86B4920.pcm"

ProgrammableWaveData_Unused_86B4930:: @ 86B4930
	.incbin "sound/programmable_wave_samples/unused_86B4930.pcm"

ProgrammableWaveData_Unused_86B4940:: @ 86B4940
	.incbin "sound/programmable_wave_samples/unused_86B4940.pcm"

ProgrammableWaveData_Unused_86B4950:: @ 86B4950
	.incbin "sound/programmable_wave_samples/unused_86B4950.pcm"

ProgrammableWaveData_Unused_86B4960:: @ 86B4960
	.incbin "sound/programmable_wave_samples/unused_86B4960.pcm"

ProgrammableWaveData_86B4970:: @ 86B4970
	.incbin "sound/programmable_wave_samples/86B4970.pcm"

ProgrammableWaveData_86B4980:: @ 86B4980
	.incbin "sound/programmable_wave_samples/86B4980.pcm"

ProgrammableWaveData_86B4990:: @ 86B4990
	.incbin "sound/programmable_wave_samples/86B4990.pcm"

ProgrammableWaveData_86B49A0:: @ 86B49A0
	.incbin "sound/programmable_wave_samples/86B49A0.pcm"

ProgrammableWaveData_86B49B0:: @ 86B49B0
	.incbin "sound/programmable_wave_samples/86B49B0.pcm"

ProgrammableWaveData_organwave::
	.incbin "sound/programmable_wave_samples/organwave.pcm"

ProgrammableWaveData_triangle::
	.incbin "sound/programmable_wave_samples/triangle.pcm"

ProgrammableWaveData_sine::
	.incbin "sound/programmable_wave_samples/sine.pcm"

ProgrammableWaveData_square12::
	.incbin "sound/programmable_wave_samples/square12.pcm"

ProgrammableWaveData_square25::
	.incbin "sound/programmable_wave_samples/square25.pcm"

ProgrammableWaveData_square37::
	.incbin "sound/programmable_wave_samples/square37.pcm"

ProgrammableWaveData_square50::
	.incbin "sound/programmable_wave_samples/square50.pcm"

ProgrammableWaveData_crystal1::
	.incbin "sound/programmable_wave_samples/crystal1.pcm"
