	.align 4
ProgrammableWaveData_0860B390::
	.incbin "sound/programmable_wave_samples/0860B390.pcm"

ProgrammableWaveData_0860B3A0::
	.incbin "sound/programmable_wave_samples/0860B3A0.pcm"

ProgrammableWaveData_0860B3B0::
	.incbin "sound/programmable_wave_samples/0860B3B0.pcm"

ProgrammableWaveData_0860B3C0::
	.incbin "sound/programmable_wave_samples/0860B3C0.pcm"

ProgrammableWaveData_0860B3D0::
	.incbin "sound/programmable_wave_samples/0860B3D0.pcm"
