	.align 4
ProgrammableWaveData_8120DAC::
	.incbin "sound/programmable_wave_samples/8120DAC.pcm"

ProgrammableWaveData_8120DBC::
	.incbin "sound/programmable_wave_samples/8120DBC.pcm"

ProgrammableWaveData_8120DCC::
	.incbin "sound/programmable_wave_samples/8120DCC.pcm"

ProgrammableWaveData_8120DDC::
	.incbin "sound/programmable_wave_samples/8120DDC.pcm"

ProgrammableWaveData_8120DEC::
	.incbin "sound/programmable_wave_samples/8120DEC.pcm"

ProgrammableWaveData_8120DFC::
	.incbin "sound/programmable_wave_samples/8120DFC.pcm"

ProgrammableWaveData_unused_8120E0C::
	.incbin "sound/programmable_wave_samples/unused_8120E0C.pcm"
