	.align 2
gSongTable::
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song song0002, 0, 0
	song song0003, 0, 0
	song song0004, 0, 0
	song song0005, 0, 0
	song song0006, 0, 0
	song song0007, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song song0010, 0, 0
	song song0011, 0, 0
	song song0012, 0, 0
	song song0013, 0, 0
	song song0014, 0, 0
	song song0015, 0, 0
	song song0016, 0, 0
	song song0017, 0, 0
	song song0018, 0, 0
	song song0019, 0, 0
	song song0020, 0, 0
	song song0021, 0, 0
	song song0022, 0, 0
	song song0023, 0, 0
	song song0024, 0, 0
	song song0025, 0, 0
	song song0026, 0, 0
	song song0027, 0, 0
	song song0028, 0, 0
	song song0029, 0, 0
	song song0030, 0, 0
	song song0031, 0, 0
	song song0032, 0, 0
	song song0033, 0, 0
	song song0034, 0, 0
	song song0035, 0, 0
	song song0036, 0, 0
	song song0037, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song song0040, 0, 0
	song song0041, 0, 0
	song song0042, 0, 0
	song song0043, 0, 0
	song song0044, 0, 0
	song song0045, 0, 0
	song song0046, 0, 0
	song song0047, 0, 0
	song song0048, 0, 0
	song dummy_song_header, 0, 0
	song dummy_song_header, 0, 0
	song song0051, 0, 0
	song song0052, 0, 0
	song song0053, 0, 0
	song song0054, 0, 0
	song song0055, 0, 0
	song song0056, 0, 0
	song song0057, 0, 0
	song dummy_song_header, 0, 0
	song song0059, 0, 0
	song song0060, 0, 0

	.align 2
dummy_song_header::
	.byte 0, 0, 0, 0
