	.align 2
gUnknown_02010020::

	.align 2
gUnknown_020100EC::
	voice_keysplit_all gUnknown_02010020
	voice_square_2 60, 0, 2, 0, 5, 3, 0
	voice_square_2 60, 0, 1, 0, 5, 3, 0
	voice_square_2 60, 0, 0, 0, 5, 3, 0
	voice_square_1 60, 0, 0, 2, 0, 5, 3, 0
	voice_square_1 60, 0, 0, 1, 0, 5, 3, 0
	voice_square_1 60, 0, 0, 0, 0, 5, 3, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_0201020C, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_0201022C, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_0201021C, 0, 0, 15, 0
	voice_noise 0, 0, 1, 0, 0, 15, 0
	voice_noise 0, 0, 0, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 119, 2, 1, 6, 0, 0
	voice_noise 60, 0, 0, 3, 6, 0, 0
	voice_square_1 60, 0, 29, 2, 0, 2, 0, 0
	voice_square_2 60, 0, 0, 0, 2, 1, 0
	voice_square_1 60, 0, 0, 0, 0, 2, 1, 0
	voice_noise_alt 70, 0, 0, 0, 0, 0, 0
	voice_noise_alt 70, 0, 0, 0, 3, 3, 0
	voice_noise_alt 100, 0, 0, 0, 1, 0, 0
	voice_noise_alt 100, 0, 0, 0, 1, 0, 0
	voice_noise_alt 127, 0, 0, 0, 1, 4, 0
